/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Asset,
  AssetEmbeddedItemsInnerAllOf,
  GetProducts401Response,
  PatchAssetCodeRequest,
  PatchReferenceEntityRecords200ResponseInner,
} from '../models';
import {
    AssetFromJSON,
    AssetToJSON,
    AssetEmbeddedItemsInnerAllOfFromJSON,
    AssetEmbeddedItemsInnerAllOfToJSON,
    GetProducts401ResponseFromJSON,
    GetProducts401ResponseToJSON,
    PatchAssetCodeRequestFromJSON,
    PatchAssetCodeRequestToJSON,
    PatchReferenceEntityRecords200ResponseInnerFromJSON,
    PatchReferenceEntityRecords200ResponseInnerToJSON,
} from '../models';

export interface DeleteAssetsCodeRequest {
    assetFamilyCode: string;
    code: string;
}

export interface GetAssetsRequest {
    assetFamilyCode: string;
    search?: string;
    channel?: string;
    locales?: string;
    searchAfter?: string;
}

export interface GetAssetsCodeRequest {
    assetFamilyCode: string;
    code: string;
}

export interface PatchAssetCodeOperationRequest {
    assetFamilyCode: string;
    code: string;
    body: PatchAssetCodeRequest;
}

export interface PatchAssetsRequest {
    assetFamilyCode: string;
    body: Array<AssetEmbeddedItemsInnerAllOf>;
}

/**
 * 
 */
export class AssetApi extends runtime.BaseAPI {

    /**
     * This endpoint allows you to delete a given asset. This endpoint is case sensitive on the asset family code.
     * Delete an asset
     */
    async deleteAssetsCodeRaw(requestParameters: DeleteAssetsCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.assetFamilyCode === null || requestParameters.assetFamilyCode === undefined) {
            throw new runtime.RequiredError('assetFamilyCode','Required parameter requestParameters.assetFamilyCode was null or undefined when calling deleteAssetsCode.');
        }

        if (requestParameters.code === null || requestParameters.code === undefined) {
            throw new runtime.RequiredError('code','Required parameter requestParameters.code was null or undefined when calling deleteAssetsCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/rest/v1/asset-families/{asset_family_code}/assets/{code}`.replace(`{${"asset_family_code"}}`, encodeURIComponent(String(requestParameters.assetFamilyCode))).replace(`{${"code"}}`, encodeURIComponent(String(requestParameters.code))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint allows you to delete a given asset. This endpoint is case sensitive on the asset family code.
     * Delete an asset
     */
    async deleteAssetsCode(requestParameters: DeleteAssetsCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAssetsCodeRaw(requestParameters, initOverrides);
    }

    /**
     * This endpoint allows you to get a list of assets of a given asset family. Assets are paginated. This endpoint is case sensitive on the asset family code.
     * Get the list of the assets of a given asset family
     */
    async getAssetsRaw(requestParameters: GetAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Asset>> {
        if (requestParameters.assetFamilyCode === null || requestParameters.assetFamilyCode === undefined) {
            throw new runtime.RequiredError('assetFamilyCode','Required parameter requestParameters.assetFamilyCode was null or undefined when calling getAssets.');
        }

        const queryParameters: any = {};

        if (requestParameters.search !== undefined) {
            queryParameters['search'] = requestParameters.search;
        }

        if (requestParameters.channel !== undefined) {
            queryParameters['channel'] = requestParameters.channel;
        }

        if (requestParameters.locales !== undefined) {
            queryParameters['locales'] = requestParameters.locales;
        }

        if (requestParameters.searchAfter !== undefined) {
            queryParameters['search_after'] = requestParameters.searchAfter;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/rest/v1/asset-families/{asset_family_code}/assets`.replace(`{${"asset_family_code"}}`, encodeURIComponent(String(requestParameters.assetFamilyCode))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetFromJSON(jsonValue));
    }

    /**
     * This endpoint allows you to get a list of assets of a given asset family. Assets are paginated. This endpoint is case sensitive on the asset family code.
     * Get the list of the assets of a given asset family
     */
    async getAssets(requestParameters: GetAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Asset> {
        const response = await this.getAssetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allows you to get the information about a given asset for a given asset family. This endpoint is case sensitive on the asset family code.
     * Get an asset of a given asset family
     */
    async getAssetsCodeRaw(requestParameters: GetAssetsCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AssetEmbeddedItemsInnerAllOf>> {
        if (requestParameters.assetFamilyCode === null || requestParameters.assetFamilyCode === undefined) {
            throw new runtime.RequiredError('assetFamilyCode','Required parameter requestParameters.assetFamilyCode was null or undefined when calling getAssetsCode.');
        }

        if (requestParameters.code === null || requestParameters.code === undefined) {
            throw new runtime.RequiredError('code','Required parameter requestParameters.code was null or undefined when calling getAssetsCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/rest/v1/asset-families/{asset_family_code}/assets/{code}`.replace(`{${"asset_family_code"}}`, encodeURIComponent(String(requestParameters.assetFamilyCode))).replace(`{${"code"}}`, encodeURIComponent(String(requestParameters.code))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AssetEmbeddedItemsInnerAllOfFromJSON(jsonValue));
    }

    /**
     * This endpoint allows you to get the information about a given asset for a given asset family. This endpoint is case sensitive on the asset family code.
     * Get an asset of a given asset family
     */
    async getAssetsCode(requestParameters: GetAssetsCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AssetEmbeddedItemsInnerAllOf> {
        const response = await this.getAssetsCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allows you to update a given asset of a given asset family. Learn more about the <a href=\"/documentation/update.html#patch-asset-attribute-values\">Update behavior</a>. Note that if the asset does not already exist for the given asset family, it creates it. This endpoint is case sensitive on the asset family code.
     * Update/create an asset
     */
    async patchAssetCodeRaw(requestParameters: PatchAssetCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.assetFamilyCode === null || requestParameters.assetFamilyCode === undefined) {
            throw new runtime.RequiredError('assetFamilyCode','Required parameter requestParameters.assetFamilyCode was null or undefined when calling patchAssetCode.');
        }

        if (requestParameters.code === null || requestParameters.code === undefined) {
            throw new runtime.RequiredError('code','Required parameter requestParameters.code was null or undefined when calling patchAssetCode.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling patchAssetCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/rest/v1/asset-families/{asset_family_code}/assets/{code}`.replace(`{${"asset_family_code"}}`, encodeURIComponent(String(requestParameters.assetFamilyCode))).replace(`{${"code"}}`, encodeURIComponent(String(requestParameters.code))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchAssetCodeRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint allows you to update a given asset of a given asset family. Learn more about the <a href=\"/documentation/update.html#patch-asset-attribute-values\">Update behavior</a>. Note that if the asset does not already exist for the given asset family, it creates it. This endpoint is case sensitive on the asset family code.
     * Update/create an asset
     */
    async patchAssetCode(requestParameters: PatchAssetCodeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchAssetCodeRaw(requestParameters, initOverrides);
    }

    /**
     * This endpoint allows you to update and/or create several assets of one given asset family at once. Learn more about the <a href=\"/documentation/update.html#patch-asset-attribute-values\">Update behavior</a>. Note that if the asset does not already exist for the given asset family, it creates it. This endpoint is case sensitive on the asset family code.
     * Update/create several assets
     */
    async patchAssetsRaw(requestParameters: PatchAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PatchReferenceEntityRecords200ResponseInner>>> {
        if (requestParameters.assetFamilyCode === null || requestParameters.assetFamilyCode === undefined) {
            throw new runtime.RequiredError('assetFamilyCode','Required parameter requestParameters.assetFamilyCode was null or undefined when calling patchAssets.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling patchAssets.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/rest/v1/asset-families/{asset_family_code}/assets`.replace(`{${"asset_family_code"}}`, encodeURIComponent(String(requestParameters.assetFamilyCode))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body.map(AssetEmbeddedItemsInnerAllOfToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PatchReferenceEntityRecords200ResponseInnerFromJSON));
    }

    /**
     * This endpoint allows you to update and/or create several assets of one given asset family at once. Learn more about the <a href=\"/documentation/update.html#patch-asset-attribute-values\">Update behavior</a>. Note that if the asset does not already exist for the given asset family, it creates it. This endpoint is case sensitive on the asset family code.
     * Update/create several assets
     */
    async patchAssets(requestParameters: PatchAssetsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PatchReferenceEntityRecords200ResponseInner>> {
        const response = await this.patchAssetsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
