/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAssetFamiliesCodeAttributes200ResponseInner,
  GetProducts401Response,
} from '../models';
import {
    GetAssetFamiliesCodeAttributes200ResponseInnerFromJSON,
    GetAssetFamiliesCodeAttributes200ResponseInnerToJSON,
    GetProducts401ResponseFromJSON,
    GetProducts401ResponseToJSON,
} from '../models';

export interface GetAssetFamiliesCodeAttributesRequest {
    assetFamilyCode: string;
}

export interface GetAssetFamilyAttributesCodeRequest {
    assetFamilyCode: string;
    code: string;
}

export interface PatchAssetFamilyAttributesCodeRequest {
    assetFamilyCode: string;
    code: string;
    body: GetAssetFamiliesCodeAttributes200ResponseInner;
}

/**
 * 
 */
export class AssetAttributeApi extends runtime.BaseAPI {

    /**
     * This endpoint allows you to get the list of attributes of a given asset family.
     * Get the list of attributes of a given asset family
     */
    async getAssetFamiliesCodeAttributesRaw(requestParameters: GetAssetFamiliesCodeAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GetAssetFamiliesCodeAttributes200ResponseInner>>> {
        if (requestParameters.assetFamilyCode === null || requestParameters.assetFamilyCode === undefined) {
            throw new runtime.RequiredError('assetFamilyCode','Required parameter requestParameters.assetFamilyCode was null or undefined when calling getAssetFamiliesCodeAttributes.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/rest/v1/asset-families/{asset_family_code}/attributes`.replace(`{${"asset_family_code"}}`, encodeURIComponent(String(requestParameters.assetFamilyCode))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GetAssetFamiliesCodeAttributes200ResponseInnerFromJSON));
    }

    /**
     * This endpoint allows you to get the list of attributes of a given asset family.
     * Get the list of attributes of a given asset family
     */
    async getAssetFamiliesCodeAttributes(requestParameters: GetAssetFamiliesCodeAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GetAssetFamiliesCodeAttributes200ResponseInner>> {
        const response = await this.getAssetFamiliesCodeAttributesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allows you to get the information about a given attribute for a given asset family.
     * Get an attribute of a given asset family
     */
    async getAssetFamilyAttributesCodeRaw(requestParameters: GetAssetFamilyAttributesCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAssetFamiliesCodeAttributes200ResponseInner>> {
        if (requestParameters.assetFamilyCode === null || requestParameters.assetFamilyCode === undefined) {
            throw new runtime.RequiredError('assetFamilyCode','Required parameter requestParameters.assetFamilyCode was null or undefined when calling getAssetFamilyAttributesCode.');
        }

        if (requestParameters.code === null || requestParameters.code === undefined) {
            throw new runtime.RequiredError('code','Required parameter requestParameters.code was null or undefined when calling getAssetFamilyAttributesCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/rest/v1/asset-families/{asset_family_code}/attributes/{code}`.replace(`{${"asset_family_code"}}`, encodeURIComponent(String(requestParameters.assetFamilyCode))).replace(`{${"code"}}`, encodeURIComponent(String(requestParameters.code))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAssetFamiliesCodeAttributes200ResponseInnerFromJSON(jsonValue));
    }

    /**
     * This endpoint allows you to get the information about a given attribute for a given asset family.
     * Get an attribute of a given asset family
     */
    async getAssetFamilyAttributesCode(requestParameters: GetAssetFamilyAttributesCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAssetFamiliesCodeAttributes200ResponseInner> {
        const response = await this.getAssetFamilyAttributesCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * This endpoint allows you to update a given attribute for a given asset family. Note that if the attribute does not already exist for the given asset family, it creates it.
     * Update/create an attribute of a given asset family
     */
    async patchAssetFamilyAttributesCodeRaw(requestParameters: PatchAssetFamilyAttributesCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.assetFamilyCode === null || requestParameters.assetFamilyCode === undefined) {
            throw new runtime.RequiredError('assetFamilyCode','Required parameter requestParameters.assetFamilyCode was null or undefined when calling patchAssetFamilyAttributesCode.');
        }

        if (requestParameters.code === null || requestParameters.code === undefined) {
            throw new runtime.RequiredError('code','Required parameter requestParameters.code was null or undefined when calling patchAssetFamilyAttributesCode.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling patchAssetFamilyAttributesCode.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/rest/v1/asset-families/{asset_family_code}/attributes/{code}`.replace(`{${"asset_family_code"}}`, encodeURIComponent(String(requestParameters.assetFamilyCode))).replace(`{${"code"}}`, encodeURIComponent(String(requestParameters.code))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: GetAssetFamiliesCodeAttributes200ResponseInnerToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * This endpoint allows you to update a given attribute for a given asset family. Note that if the attribute does not already exist for the given asset family, it creates it.
     * Update/create an attribute of a given asset family
     */
    async patchAssetFamilyAttributesCode(requestParameters: PatchAssetFamilyAttributesCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchAssetFamilyAttributesCodeRaw(requestParameters, initOverrides);
    }

}
