/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner
 */
export interface AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner {
    /**
     * 
     * @type {string}
     * @memberof AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner
     */
    field: string;
    /**
     * 
     * @type {string}
     * @memberof AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner
     */
    operator: string;
    /**
     * 
     * @type {string}
     * @memberof AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner
     */
    locale?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner
     */
    channel?: string;
}

/**
 * Check if a given object implements the AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner interface.
 */
export function instanceOfAssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "field" in value;
    isInstance = isInstance && "operator" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInnerFromJSON(json: any): AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner {
    return AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInnerFromJSONTyped(json, false);
}

export function AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'field': json['field'],
        'operator': json['operator'],
        'value': json['value'],
        'locale': !exists(json, 'locale') ? undefined : json['locale'],
        'channel': !exists(json, 'channel') ? undefined : json['channel'],
    };
}

export function AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInnerToJSON(value?: AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerProductSelectionsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field': value.field,
        'operator': value.operator,
        'value': value.value,
        'locale': value.locale,
        'channel': value.channel,
    };
}

