/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssetFamilyListAllOfOperations } from './AssetFamilyListAllOfOperations';
import {
    AssetFamilyListAllOfOperationsFromJSON,
    AssetFamilyListAllOfOperationsFromJSONTyped,
    AssetFamilyListAllOfOperationsToJSON,
} from './AssetFamilyListAllOfOperations';
import type { AssetFamilyListAllOfSource } from './AssetFamilyListAllOfSource';
import {
    AssetFamilyListAllOfSourceFromJSON,
    AssetFamilyListAllOfSourceFromJSONTyped,
    AssetFamilyListAllOfSourceToJSON,
} from './AssetFamilyListAllOfSource';
import type { AssetFamilyListAllOfTarget } from './AssetFamilyListAllOfTarget';
import {
    AssetFamilyListAllOfTargetFromJSON,
    AssetFamilyListAllOfTargetFromJSONTyped,
    AssetFamilyListAllOfTargetToJSON,
} from './AssetFamilyListAllOfTarget';

/**
 * 
 * @export
 * @interface AssetFamilyListAllOfTransformations
 */
export interface AssetFamilyListAllOfTransformations {
    /**
     * The name of the transformation
     * @type {string}
     * @memberof AssetFamilyListAllOfTransformations
     */
    label: string;
    /**
     * The suffix that will be appended to the source filename to generate the target filename. More details <a href='/concepts/asset-manager.html#target-filename'>here</a>.
     * @type {string}
     * @memberof AssetFamilyListAllOfTransformations
     */
    filenameSuffix?: string;
    /**
     * The prefix that will be prepended to the source filename to generate the target filename. More details <a href='/concepts/asset-manager.html#target-filename'>here</a>.
     * @type {string}
     * @memberof AssetFamilyListAllOfTransformations
     */
    filenamePrefix?: string;
    /**
     * 
     * @type {AssetFamilyListAllOfSource}
     * @memberof AssetFamilyListAllOfTransformations
     */
    source: AssetFamilyListAllOfSource;
    /**
     * 
     * @type {AssetFamilyListAllOfTarget}
     * @memberof AssetFamilyListAllOfTransformations
     */
    target: AssetFamilyListAllOfTarget;
    /**
     * 
     * @type {AssetFamilyListAllOfOperations}
     * @memberof AssetFamilyListAllOfTransformations
     */
    operations: AssetFamilyListAllOfOperations;
}

/**
 * Check if a given object implements the AssetFamilyListAllOfTransformations interface.
 */
export function instanceOfAssetFamilyListAllOfTransformations(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "target" in value;
    isInstance = isInstance && "operations" in value;

    return isInstance;
}

export function AssetFamilyListAllOfTransformationsFromJSON(json: any): AssetFamilyListAllOfTransformations {
    return AssetFamilyListAllOfTransformationsFromJSONTyped(json, false);
}

export function AssetFamilyListAllOfTransformationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetFamilyListAllOfTransformations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
        'filenameSuffix': !exists(json, 'filename_suffix') ? undefined : json['filename_suffix'],
        'filenamePrefix': !exists(json, 'filename_prefix') ? undefined : json['filename_prefix'],
        'source': AssetFamilyListAllOfSourceFromJSON(json['source']),
        'target': AssetFamilyListAllOfTargetFromJSON(json['target']),
        'operations': AssetFamilyListAllOfOperationsFromJSON(json['operations']),
    };
}

export function AssetFamilyListAllOfTransformationsToJSON(value?: AssetFamilyListAllOfTransformations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'filename_suffix': value.filenameSuffix,
        'filename_prefix': value.filenamePrefix,
        'source': AssetFamilyListAllOfSourceToJSON(value.source),
        'target': AssetFamilyListAllOfTargetToJSON(value.target),
        'operations': AssetFamilyListAllOfOperationsToJSON(value.operations),
    };
}

