/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssetEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInner } from './AssetEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInner';
import {
    AssetEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInnerFromJSON,
    AssetEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInnerFromJSONTyped,
    AssetEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInnerToJSON,
} from './AssetEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInner';

/**
 * Asset attributes values, see the <a href='/concepts/asset-manager.html#focus-on-the-asset-values'>Focus on the asset values</a> section for more details.
 * @export
 * @interface AssetEmbeddedItemsInnerAllOfValues
 */
export interface AssetEmbeddedItemsInnerAllOfValues {
    /**
     * 
     * @type {Array<AssetEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInner>}
     * @memberof AssetEmbeddedItemsInnerAllOfValues
     */
    additionalProperties?: Array<AssetEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInner>;
}

/**
 * Check if a given object implements the AssetEmbeddedItemsInnerAllOfValues interface.
 */
export function instanceOfAssetEmbeddedItemsInnerAllOfValues(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AssetEmbeddedItemsInnerAllOfValuesFromJSON(json: any): AssetEmbeddedItemsInnerAllOfValues {
    return AssetEmbeddedItemsInnerAllOfValuesFromJSONTyped(json, false);
}

export function AssetEmbeddedItemsInnerAllOfValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetEmbeddedItemsInnerAllOfValues {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'additionalProperties': !exists(json, 'additionalProperties') ? undefined : ((json['additionalProperties'] as Array<any>).map(AssetEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInnerFromJSON)),
    };
}

export function AssetEmbeddedItemsInnerAllOfValuesToJSON(value?: AssetEmbeddedItemsInnerAllOfValues | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'additionalProperties': value.additionalProperties === undefined ? undefined : ((value.additionalProperties as Array<any>).map(AssetEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInnerToJSON)),
    };
}

