/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Association type labels for each locale
 * @export
 * @interface AssociationTypesEmbeddedItemsInnerAllOfLabels
 */
export interface AssociationTypesEmbeddedItemsInnerAllOfLabels {
    /**
     * Association type label for the locale `localeCode`
     * @type {string}
     * @memberof AssociationTypesEmbeddedItemsInnerAllOfLabels
     */
    localeCode?: string;
}

/**
 * Check if a given object implements the AssociationTypesEmbeddedItemsInnerAllOfLabels interface.
 */
export function instanceOfAssociationTypesEmbeddedItemsInnerAllOfLabels(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AssociationTypesEmbeddedItemsInnerAllOfLabelsFromJSON(json: any): AssociationTypesEmbeddedItemsInnerAllOfLabels {
    return AssociationTypesEmbeddedItemsInnerAllOfLabelsFromJSONTyped(json, false);
}

export function AssociationTypesEmbeddedItemsInnerAllOfLabelsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssociationTypesEmbeddedItemsInnerAllOfLabels {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'localeCode': !exists(json, 'localeCode') ? undefined : json['localeCode'],
    };
}

export function AssociationTypesEmbeddedItemsInnerAllOfLabelsToJSON(value?: AssociationTypesEmbeddedItemsInnerAllOfLabels | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'localeCode': value.localeCode,
    };
}

