/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AttributeOptionsEmbedded } from './AttributeOptionsEmbedded';
import {
    AttributeOptionsEmbeddedFromJSON,
    AttributeOptionsEmbeddedFromJSONTyped,
    AttributeOptionsEmbeddedToJSON,
} from './AttributeOptionsEmbedded';
import type { ProductsLinks } from './ProductsLinks';
import {
    ProductsLinksFromJSON,
    ProductsLinksFromJSONTyped,
    ProductsLinksToJSON,
} from './ProductsLinks';

/**
 * 
 * @export
 * @interface AttributeOptions
 */
export interface AttributeOptions {
    /**
     * 
     * @type {AttributeOptionsEmbedded}
     * @memberof AttributeOptions
     */
    embedded?: AttributeOptionsEmbedded;
    /**
     * 
     * @type {ProductsLinks}
     * @memberof AttributeOptions
     */
    links?: ProductsLinks;
    /**
     * Current page number
     * @type {number}
     * @memberof AttributeOptions
     */
    currentPage?: number;
}

/**
 * Check if a given object implements the AttributeOptions interface.
 */
export function instanceOfAttributeOptions(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AttributeOptionsFromJSON(json: any): AttributeOptions {
    return AttributeOptionsFromJSONTyped(json, false);
}

export function AttributeOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'embedded': !exists(json, '_embedded') ? undefined : AttributeOptionsEmbeddedFromJSON(json['_embedded']),
        'links': !exists(json, '_links') ? undefined : ProductsLinksFromJSON(json['_links']),
        'currentPage': !exists(json, 'current_page') ? undefined : json['current_page'],
    };
}

export function AttributeOptionsToJSON(value?: AttributeOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_embedded': AttributeOptionsEmbeddedToJSON(value.embedded),
        '_links': ProductsLinksToJSON(value.links),
        'current_page': value.currentPage,
    };
}

