/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Attribute option labels for each locale
 * @export
 * @interface AttributeOptionListAllOfLabels
 */
export interface AttributeOptionListAllOfLabels {
    /**
     * Attribute option label for the locale `localeCode`
     * @type {string}
     * @memberof AttributeOptionListAllOfLabels
     */
    localeCode?: string;
}

/**
 * Check if a given object implements the AttributeOptionListAllOfLabels interface.
 */
export function instanceOfAttributeOptionListAllOfLabels(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AttributeOptionListAllOfLabelsFromJSON(json: any): AttributeOptionListAllOfLabels {
    return AttributeOptionListAllOfLabelsFromJSONTyped(json, false);
}

export function AttributeOptionListAllOfLabelsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributeOptionListAllOfLabels {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'localeCode': !exists(json, 'localeCode') ? undefined : json['localeCode'],
    };
}

export function AttributeOptionListAllOfLabelsToJSON(value?: AttributeOptionListAllOfLabels | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'localeCode': value.localeCode,
    };
}

