/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerLabels } from './AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerLabels';
import {
    AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerLabelsFromJSON,
    AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerLabelsFromJSONTyped,
    AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerLabelsToJSON,
} from './AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerLabels';
import type { AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerValidations } from './AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerValidations';
import {
    AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerValidationsFromJSON,
    AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerValidationsFromJSONTyped,
    AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerValidationsToJSON,
} from './AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerValidations';

/**
 * 
 * @export
 * @interface AttributesEmbeddedItemsInnerAllOfTableConfigurationInner
 */
export interface AttributesEmbeddedItemsInnerAllOfTableConfigurationInner {
    /**
     * Column code
     * @type {string}
     * @memberof AttributesEmbeddedItemsInnerAllOfTableConfigurationInner
     */
    code: string;
    /**
     * Column data type
     * @type {string}
     * @memberof AttributesEmbeddedItemsInnerAllOfTableConfigurationInner
     */
    dataType: AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerDataTypeEnum;
    /**
     * 
     * @type {AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerValidations}
     * @memberof AttributesEmbeddedItemsInnerAllOfTableConfigurationInner
     */
    validations?: AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerValidations;
    /**
     * 
     * @type {AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerLabels}
     * @memberof AttributesEmbeddedItemsInnerAllOfTableConfigurationInner
     */
    labels?: AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerLabels;
    /**
     * Defines if the column should be entirely filled for the attribute to be considered complete
     * @type {boolean}
     * @memberof AttributesEmbeddedItemsInnerAllOfTableConfigurationInner
     */
    isRequiredForCompleteness?: boolean;
}


/**
 * @export
 */
export const AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerDataTypeEnum = {
    Select: 'select',
    Text: 'text',
    Number: 'number',
    Boolean: 'boolean'
} as const;
export type AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerDataTypeEnum = typeof AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerDataTypeEnum[keyof typeof AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerDataTypeEnum];


/**
 * Check if a given object implements the AttributesEmbeddedItemsInnerAllOfTableConfigurationInner interface.
 */
export function instanceOfAttributesEmbeddedItemsInnerAllOfTableConfigurationInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "dataType" in value;

    return isInstance;
}

export function AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerFromJSON(json: any): AttributesEmbeddedItemsInnerAllOfTableConfigurationInner {
    return AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerFromJSONTyped(json, false);
}

export function AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AttributesEmbeddedItemsInnerAllOfTableConfigurationInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'dataType': json['data_type'],
        'validations': !exists(json, 'validations') ? undefined : AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerValidationsFromJSON(json['validations']),
        'labels': !exists(json, 'labels') ? undefined : AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerLabelsFromJSON(json['labels']),
        'isRequiredForCompleteness': !exists(json, 'is_required_for_completeness') ? undefined : json['is_required_for_completeness'],
    };
}

export function AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerToJSON(value?: AttributesEmbeddedItemsInnerAllOfTableConfigurationInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'data_type': value.dataType,
        'validations': AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerValidationsToJSON(value.validations),
        'labels': AttributesEmbeddedItemsInnerAllOfTableConfigurationInnerLabelsToJSON(value.labels),
        'is_required_for_completeness': value.isRequiredForCompleteness,
    };
}

