/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductsEmbeddedItemsInnerAllOfLinks } from './ProductsEmbeddedItemsInnerAllOfLinks';
import {
    ProductsEmbeddedItemsInnerAllOfLinksFromJSON,
    ProductsEmbeddedItemsInnerAllOfLinksFromJSONTyped,
    ProductsEmbeddedItemsInnerAllOfLinksToJSON,
} from './ProductsEmbeddedItemsInnerAllOfLinks';

/**
 * 
 * @export
 * @interface CatalogsEmbeddedItemsInner
 */
export interface CatalogsEmbeddedItemsInner {
    /**
     * 
     * @type {ProductsEmbeddedItemsInnerAllOfLinks}
     * @memberof CatalogsEmbeddedItemsInner
     */
    links?: ProductsEmbeddedItemsInnerAllOfLinks;
    /**
     * Catalog id
     * @type {string}
     * @memberof CatalogsEmbeddedItemsInner
     */
    id?: string;
    /**
     * Catalog name
     * @type {string}
     * @memberof CatalogsEmbeddedItemsInner
     */
    name?: string;
    /**
     * Whether the catalog is enabled or not
     * @type {boolean}
     * @memberof CatalogsEmbeddedItemsInner
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the CatalogsEmbeddedItemsInner interface.
 */
export function instanceOfCatalogsEmbeddedItemsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CatalogsEmbeddedItemsInnerFromJSON(json: any): CatalogsEmbeddedItemsInner {
    return CatalogsEmbeddedItemsInnerFromJSONTyped(json, false);
}

export function CatalogsEmbeddedItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CatalogsEmbeddedItemsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, '_links') ? undefined : ProductsEmbeddedItemsInnerAllOfLinksFromJSON(json['_links']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function CatalogsEmbeddedItemsInnerToJSON(value?: CatalogsEmbeddedItemsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_links': ProductsEmbeddedItemsInnerAllOfLinksToJSON(value.links),
        'id': value.id,
        'name': value.name,
        'enabled': value.enabled,
    };
}

