/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChannelsPostRequestConversionUnits } from './ChannelsPostRequestConversionUnits';
import {
    ChannelsPostRequestConversionUnitsFromJSON,
    ChannelsPostRequestConversionUnitsFromJSONTyped,
    ChannelsPostRequestConversionUnitsToJSON,
} from './ChannelsPostRequestConversionUnits';
import type { ChannelsPostRequestLabels } from './ChannelsPostRequestLabels';
import {
    ChannelsPostRequestLabelsFromJSON,
    ChannelsPostRequestLabelsFromJSONTyped,
    ChannelsPostRequestLabelsToJSON,
} from './ChannelsPostRequestLabels';

/**
 * 
 * @export
 * @interface Channel
 */
export interface Channel {
    /**
     * Channel code
     * @type {string}
     * @memberof Channel
     */
    code: string;
    /**
     * Codes of activated locales for the channel
     * @type {Array<string>}
     * @memberof Channel
     */
    locales: Array<string>;
    /**
     * Codes of activated currencies for the channel
     * @type {Array<string>}
     * @memberof Channel
     */
    currencies: Array<string>;
    /**
     * Code of the category tree linked to the channel
     * @type {string}
     * @memberof Channel
     */
    categoryTree: string;
    /**
     * 
     * @type {ChannelsPostRequestConversionUnits}
     * @memberof Channel
     */
    conversionUnits?: ChannelsPostRequestConversionUnits;
    /**
     * 
     * @type {ChannelsPostRequestLabels}
     * @memberof Channel
     */
    labels?: ChannelsPostRequestLabels;
}

/**
 * Check if a given object implements the Channel interface.
 */
export function instanceOfChannel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "locales" in value;
    isInstance = isInstance && "currencies" in value;
    isInstance = isInstance && "categoryTree" in value;

    return isInstance;
}

export function ChannelFromJSON(json: any): Channel {
    return ChannelFromJSONTyped(json, false);
}

export function ChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Channel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'locales': json['locales'],
        'currencies': json['currencies'],
        'categoryTree': json['category_tree'],
        'conversionUnits': !exists(json, 'conversion_units') ? undefined : ChannelsPostRequestConversionUnitsFromJSON(json['conversion_units']),
        'labels': !exists(json, 'labels') ? undefined : ChannelsPostRequestLabelsFromJSON(json['labels']),
    };
}

export function ChannelToJSON(value?: Channel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'locales': value.locales,
        'currencies': value.currencies,
        'category_tree': value.categoryTree,
        'conversion_units': ChannelsPostRequestConversionUnitsToJSON(value.conversionUnits),
        'labels': ChannelsPostRequestLabelsToJSON(value.labels),
    };
}

