/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Units to which the given metric attributes should be converted when exporting products
 * @export
 * @interface ChannelListAllOfConversionUnits
 */
export interface ChannelListAllOfConversionUnits {
    /**
     * Conversion unit code used to convert the values of the attribute `attributeCode` when exporting via the channel
     * @type {string}
     * @memberof ChannelListAllOfConversionUnits
     */
    attributeCode?: string;
}

/**
 * Check if a given object implements the ChannelListAllOfConversionUnits interface.
 */
export function instanceOfChannelListAllOfConversionUnits(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChannelListAllOfConversionUnitsFromJSON(json: any): ChannelListAllOfConversionUnits {
    return ChannelListAllOfConversionUnitsFromJSONTyped(json, false);
}

export function ChannelListAllOfConversionUnitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelListAllOfConversionUnits {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributeCode': !exists(json, 'attributeCode') ? undefined : json['attributeCode'],
    };
}

export function ChannelListAllOfConversionUnitsToJSON(value?: ChannelListAllOfConversionUnits | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributeCode': value.attributeCode,
    };
}

