/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChannelsEmbeddedItemsInnerAllOfConversionUnits } from './ChannelsEmbeddedItemsInnerAllOfConversionUnits';
import {
    ChannelsEmbeddedItemsInnerAllOfConversionUnitsFromJSON,
    ChannelsEmbeddedItemsInnerAllOfConversionUnitsFromJSONTyped,
    ChannelsEmbeddedItemsInnerAllOfConversionUnitsToJSON,
} from './ChannelsEmbeddedItemsInnerAllOfConversionUnits';
import type { ChannelsEmbeddedItemsInnerAllOfLabels } from './ChannelsEmbeddedItemsInnerAllOfLabels';
import {
    ChannelsEmbeddedItemsInnerAllOfLabelsFromJSON,
    ChannelsEmbeddedItemsInnerAllOfLabelsFromJSONTyped,
    ChannelsEmbeddedItemsInnerAllOfLabelsToJSON,
} from './ChannelsEmbeddedItemsInnerAllOfLabels';
import type { ProductsEmbeddedItemsInnerAllOfLinks } from './ProductsEmbeddedItemsInnerAllOfLinks';
import {
    ProductsEmbeddedItemsInnerAllOfLinksFromJSON,
    ProductsEmbeddedItemsInnerAllOfLinksFromJSONTyped,
    ProductsEmbeddedItemsInnerAllOfLinksToJSON,
} from './ProductsEmbeddedItemsInnerAllOfLinks';

/**
 * 
 * @export
 * @interface ChannelsEmbeddedItemsInner
 */
export interface ChannelsEmbeddedItemsInner {
    /**
     * 
     * @type {ProductsEmbeddedItemsInnerAllOfLinks}
     * @memberof ChannelsEmbeddedItemsInner
     */
    links?: ProductsEmbeddedItemsInnerAllOfLinks;
    /**
     * Channel code
     * @type {string}
     * @memberof ChannelsEmbeddedItemsInner
     */
    code: string;
    /**
     * Codes of activated locales for the channel
     * @type {Array<string>}
     * @memberof ChannelsEmbeddedItemsInner
     */
    locales: Array<string>;
    /**
     * Codes of activated currencies for the channel
     * @type {Array<string>}
     * @memberof ChannelsEmbeddedItemsInner
     */
    currencies: Array<string>;
    /**
     * Code of the category tree linked to the channel
     * @type {string}
     * @memberof ChannelsEmbeddedItemsInner
     */
    categoryTree: string;
    /**
     * 
     * @type {ChannelsEmbeddedItemsInnerAllOfConversionUnits}
     * @memberof ChannelsEmbeddedItemsInner
     */
    conversionUnits?: ChannelsEmbeddedItemsInnerAllOfConversionUnits;
    /**
     * 
     * @type {ChannelsEmbeddedItemsInnerAllOfLabels}
     * @memberof ChannelsEmbeddedItemsInner
     */
    labels?: ChannelsEmbeddedItemsInnerAllOfLabels;
}

/**
 * Check if a given object implements the ChannelsEmbeddedItemsInner interface.
 */
export function instanceOfChannelsEmbeddedItemsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "locales" in value;
    isInstance = isInstance && "currencies" in value;
    isInstance = isInstance && "categoryTree" in value;

    return isInstance;
}

export function ChannelsEmbeddedItemsInnerFromJSON(json: any): ChannelsEmbeddedItemsInner {
    return ChannelsEmbeddedItemsInnerFromJSONTyped(json, false);
}

export function ChannelsEmbeddedItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelsEmbeddedItemsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, '_links') ? undefined : ProductsEmbeddedItemsInnerAllOfLinksFromJSON(json['_links']),
        'code': json['code'],
        'locales': json['locales'],
        'currencies': json['currencies'],
        'categoryTree': json['category_tree'],
        'conversionUnits': !exists(json, 'conversion_units') ? undefined : ChannelsEmbeddedItemsInnerAllOfConversionUnitsFromJSON(json['conversion_units']),
        'labels': !exists(json, 'labels') ? undefined : ChannelsEmbeddedItemsInnerAllOfLabelsFromJSON(json['labels']),
    };
}

export function ChannelsEmbeddedItemsInnerToJSON(value?: ChannelsEmbeddedItemsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_links': ProductsEmbeddedItemsInnerAllOfLinksToJSON(value.links),
        'code': value.code,
        'locales': value.locales,
        'currencies': value.currencies,
        'category_tree': value.categoryTree,
        'conversion_units': ChannelsEmbeddedItemsInnerAllOfConversionUnitsToJSON(value.conversionUnits),
        'labels': ChannelsEmbeddedItemsInnerAllOfLabelsToJSON(value.labels),
    };
}

