/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrencyListAllOf
 */
export interface CurrencyListAllOf {
    /**
     * Currency code
     * @type {string}
     * @memberof CurrencyListAllOf
     */
    code: string;
    /**
     * Whether the currency is enabled
     * @type {boolean}
     * @memberof CurrencyListAllOf
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the CurrencyListAllOf interface.
 */
export function instanceOfCurrencyListAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function CurrencyListAllOfFromJSON(json: any): CurrencyListAllOf {
    return CurrencyListAllOfFromJSONTyped(json, false);
}

export function CurrencyListAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyListAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function CurrencyListAllOfToJSON(value?: CurrencyListAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'enabled': value.enabled,
    };
}

