/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeprecatedAssetTagListAllOf
 */
export interface DeprecatedAssetTagListAllOf {
    /**
     * PAM asset tag code
     * @type {string}
     * @memberof DeprecatedAssetTagListAllOf
     */
    code: string;
}

/**
 * Check if a given object implements the DeprecatedAssetTagListAllOf interface.
 */
export function instanceOfDeprecatedAssetTagListAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function DeprecatedAssetTagListAllOfFromJSON(json: any): DeprecatedAssetTagListAllOf {
    return DeprecatedAssetTagListAllOfFromJSONTyped(json, false);
}

export function DeprecatedAssetTagListAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeprecatedAssetTagListAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
    };
}

export function DeprecatedAssetTagListAllOfToJSON(value?: DeprecatedAssetTagListAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}

