/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DeprecatedAssetListAllOfLinkDownload } from './DeprecatedAssetListAllOfLinkDownload';
import {
    DeprecatedAssetListAllOfLinkDownloadFromJSON,
    DeprecatedAssetListAllOfLinkDownloadFromJSONTyped,
    DeprecatedAssetListAllOfLinkDownloadToJSON,
} from './DeprecatedAssetListAllOfLinkDownload';
import type { DeprecatedAssetListAllOfLinkSelf } from './DeprecatedAssetListAllOfLinkSelf';
import {
    DeprecatedAssetListAllOfLinkSelfFromJSON,
    DeprecatedAssetListAllOfLinkSelfFromJSONTyped,
    DeprecatedAssetListAllOfLinkSelfToJSON,
} from './DeprecatedAssetListAllOfLinkSelf';

/**
 * Links to get and download the variation file
 * @export
 * @interface DeprecatedAssetListAllOfLink
 */
export interface DeprecatedAssetListAllOfLink {
    /**
     * 
     * @type {DeprecatedAssetListAllOfLinkSelf}
     * @memberof DeprecatedAssetListAllOfLink
     */
    self?: DeprecatedAssetListAllOfLinkSelf;
    /**
     * 
     * @type {DeprecatedAssetListAllOfLinkDownload}
     * @memberof DeprecatedAssetListAllOfLink
     */
    download?: DeprecatedAssetListAllOfLinkDownload;
}

/**
 * Check if a given object implements the DeprecatedAssetListAllOfLink interface.
 */
export function instanceOfDeprecatedAssetListAllOfLink(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeprecatedAssetListAllOfLinkFromJSON(json: any): DeprecatedAssetListAllOfLink {
    return DeprecatedAssetListAllOfLinkFromJSONTyped(json, false);
}

export function DeprecatedAssetListAllOfLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeprecatedAssetListAllOfLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': !exists(json, 'self') ? undefined : DeprecatedAssetListAllOfLinkSelfFromJSON(json['self']),
        'download': !exists(json, 'download') ? undefined : DeprecatedAssetListAllOfLinkDownloadFromJSON(json['download']),
    };
}

export function DeprecatedAssetListAllOfLinkToJSON(value?: DeprecatedAssetListAllOfLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': DeprecatedAssetListAllOfLinkSelfToJSON(value.self),
        'download': DeprecatedAssetListAllOfLinkDownloadToJSON(value.download),
    };
}

