/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FamilyVariantsEmbeddedItemsInnerAllOfLabels } from './FamilyVariantsEmbeddedItemsInnerAllOfLabels';
import {
    FamilyVariantsEmbeddedItemsInnerAllOfLabelsFromJSON,
    FamilyVariantsEmbeddedItemsInnerAllOfLabelsFromJSONTyped,
    FamilyVariantsEmbeddedItemsInnerAllOfLabelsToJSON,
} from './FamilyVariantsEmbeddedItemsInnerAllOfLabels';
import type { FamilyVariantsEmbeddedItemsInnerAllOfVariantAttributeSetsInner } from './FamilyVariantsEmbeddedItemsInnerAllOfVariantAttributeSetsInner';
import {
    FamilyVariantsEmbeddedItemsInnerAllOfVariantAttributeSetsInnerFromJSON,
    FamilyVariantsEmbeddedItemsInnerAllOfVariantAttributeSetsInnerFromJSONTyped,
    FamilyVariantsEmbeddedItemsInnerAllOfVariantAttributeSetsInnerToJSON,
} from './FamilyVariantsEmbeddedItemsInnerAllOfVariantAttributeSetsInner';

/**
 * 
 * @export
 * @interface FamilyVariantsEmbeddedItemsInnerAllOf
 */
export interface FamilyVariantsEmbeddedItemsInnerAllOf {
    /**
     * Family variant code
     * @type {string}
     * @memberof FamilyVariantsEmbeddedItemsInnerAllOf
     */
    code: string;
    /**
     * Attributes distribution according to the enrichment level
     * @type {Array<FamilyVariantsEmbeddedItemsInnerAllOfVariantAttributeSetsInner>}
     * @memberof FamilyVariantsEmbeddedItemsInnerAllOf
     */
    variantAttributeSets: Array<FamilyVariantsEmbeddedItemsInnerAllOfVariantAttributeSetsInner>;
    /**
     * 
     * @type {FamilyVariantsEmbeddedItemsInnerAllOfLabels}
     * @memberof FamilyVariantsEmbeddedItemsInnerAllOf
     */
    labels?: FamilyVariantsEmbeddedItemsInnerAllOfLabels;
}

/**
 * Check if a given object implements the FamilyVariantsEmbeddedItemsInnerAllOf interface.
 */
export function instanceOfFamilyVariantsEmbeddedItemsInnerAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "variantAttributeSets" in value;

    return isInstance;
}

export function FamilyVariantsEmbeddedItemsInnerAllOfFromJSON(json: any): FamilyVariantsEmbeddedItemsInnerAllOf {
    return FamilyVariantsEmbeddedItemsInnerAllOfFromJSONTyped(json, false);
}

export function FamilyVariantsEmbeddedItemsInnerAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyVariantsEmbeddedItemsInnerAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'variantAttributeSets': ((json['variant_attribute_sets'] as Array<any>).map(FamilyVariantsEmbeddedItemsInnerAllOfVariantAttributeSetsInnerFromJSON)),
        'labels': !exists(json, 'labels') ? undefined : FamilyVariantsEmbeddedItemsInnerAllOfLabelsFromJSON(json['labels']),
    };
}

export function FamilyVariantsEmbeddedItemsInnerAllOfToJSON(value?: FamilyVariantsEmbeddedItemsInnerAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'variant_attribute_sets': ((value.variantAttributeSets as Array<any>).map(FamilyVariantsEmbeddedItemsInnerAllOfVariantAttributeSetsInnerToJSON)),
        'labels': FamilyVariantsEmbeddedItemsInnerAllOfLabelsToJSON(value.labels),
    };
}

