/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FamilyListAllOfAttributeRequirements } from './FamilyListAllOfAttributeRequirements';
import {
    FamilyListAllOfAttributeRequirementsFromJSON,
    FamilyListAllOfAttributeRequirementsFromJSONTyped,
    FamilyListAllOfAttributeRequirementsToJSON,
} from './FamilyListAllOfAttributeRequirements';
import type { FamilyListAllOfLabels } from './FamilyListAllOfLabels';
import {
    FamilyListAllOfLabelsFromJSON,
    FamilyListAllOfLabelsFromJSONTyped,
    FamilyListAllOfLabelsToJSON,
} from './FamilyListAllOfLabels';
import type { ProductListAllOfLinks } from './ProductListAllOfLinks';
import {
    ProductListAllOfLinksFromJSON,
    ProductListAllOfLinksFromJSONTyped,
    ProductListAllOfLinksToJSON,
} from './ProductListAllOfLinks';

/**
 * 
 * @export
 * @interface FamilyList
 */
export interface FamilyList {
    /**
     * 
     * @type {ProductListAllOfLinks}
     * @memberof FamilyList
     */
    links?: ProductListAllOfLinks;
    /**
     * Family code
     * @type {string}
     * @memberof FamilyList
     */
    code: string;
    /**
     * Attribute code used as label
     * @type {string}
     * @memberof FamilyList
     */
    attributeAsLabel: string;
    /**
     * Attribute code used as the main picture in the user interface (only since v2.0)
     * @type {string}
     * @memberof FamilyList
     */
    attributeAsImage?: string;
    /**
     * Attributes codes that compose the family
     * @type {Array<string>}
     * @memberof FamilyList
     */
    attributes?: Array<string>;
    /**
     * 
     * @type {FamilyListAllOfAttributeRequirements}
     * @memberof FamilyList
     */
    attributeRequirements?: FamilyListAllOfAttributeRequirements;
    /**
     * 
     * @type {FamilyListAllOfLabels}
     * @memberof FamilyList
     */
    labels?: FamilyListAllOfLabels;
}

/**
 * Check if a given object implements the FamilyList interface.
 */
export function instanceOfFamilyList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;
    isInstance = isInstance && "attributeAsLabel" in value;

    return isInstance;
}

export function FamilyListFromJSON(json: any): FamilyList {
    return FamilyListFromJSONTyped(json, false);
}

export function FamilyListFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, '_links') ? undefined : ProductListAllOfLinksFromJSON(json['_links']),
        'code': json['code'],
        'attributeAsLabel': json['attribute_as_label'],
        'attributeAsImage': !exists(json, 'attribute_as_image') ? undefined : json['attribute_as_image'],
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
        'attributeRequirements': !exists(json, 'attribute_requirements') ? undefined : FamilyListAllOfAttributeRequirementsFromJSON(json['attribute_requirements']),
        'labels': !exists(json, 'labels') ? undefined : FamilyListAllOfLabelsFromJSON(json['labels']),
    };
}

export function FamilyListToJSON(value?: FamilyList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_links': ProductListAllOfLinksToJSON(value.links),
        'code': value.code,
        'attribute_as_label': value.attributeAsLabel,
        'attribute_as_image': value.attributeAsImage,
        'attributes': value.attributes,
        'attribute_requirements': FamilyListAllOfAttributeRequirementsToJSON(value.attributeRequirements),
        'labels': FamilyListAllOfLabelsToJSON(value.labels),
    };
}

