/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Family variant labels for each locale
 * @export
 * @interface FamilyVariantsEmbeddedItemsInnerAllOfLabels
 */
export interface FamilyVariantsEmbeddedItemsInnerAllOfLabels {
    /**
     * Family variant label for the locale `localeCode`
     * @type {string}
     * @memberof FamilyVariantsEmbeddedItemsInnerAllOfLabels
     */
    localeCode?: string;
}

/**
 * Check if a given object implements the FamilyVariantsEmbeddedItemsInnerAllOfLabels interface.
 */
export function instanceOfFamilyVariantsEmbeddedItemsInnerAllOfLabels(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FamilyVariantsEmbeddedItemsInnerAllOfLabelsFromJSON(json: any): FamilyVariantsEmbeddedItemsInnerAllOfLabels {
    return FamilyVariantsEmbeddedItemsInnerAllOfLabelsFromJSONTyped(json, false);
}

export function FamilyVariantsEmbeddedItemsInnerAllOfLabelsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FamilyVariantsEmbeddedItemsInnerAllOfLabels {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'localeCode': !exists(json, 'localeCode') ? undefined : json['localeCode'],
    };
}

export function FamilyVariantsEmbeddedItemsInnerAllOfLabelsToJSON(value?: FamilyVariantsEmbeddedItemsInnerAllOfLabels | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'localeCode': value.localeCode,
    };
}

