/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FamiliesEmbedded } from './FamiliesEmbedded';
import {
    FamiliesEmbeddedFromJSON,
    FamiliesEmbeddedFromJSONTyped,
    FamiliesEmbeddedToJSON,
} from './FamiliesEmbedded';
import type { ProductsLinks } from './ProductsLinks';
import {
    ProductsLinksFromJSON,
    ProductsLinksFromJSONTyped,
    ProductsLinksToJSON,
} from './ProductsLinks';

/**
 * 
 * @export
 * @interface Families
 */
export interface Families {
    /**
     * 
     * @type {FamiliesEmbedded}
     * @memberof Families
     */
    embedded?: FamiliesEmbedded;
    /**
     * 
     * @type {ProductsLinks}
     * @memberof Families
     */
    links?: ProductsLinks;
    /**
     * Current page number
     * @type {number}
     * @memberof Families
     */
    currentPage?: number;
}

/**
 * Check if a given object implements the Families interface.
 */
export function instanceOfFamilies(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FamiliesFromJSON(json: any): Families {
    return FamiliesFromJSONTyped(json, false);
}

export function FamiliesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Families {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'embedded': !exists(json, '_embedded') ? undefined : FamiliesEmbeddedFromJSON(json['_embedded']),
        'links': !exists(json, '_links') ? undefined : ProductsLinksFromJSON(json['_links']),
        'currentPage': !exists(json, 'current_page') ? undefined : json['current_page'],
    };
}

export function FamiliesToJSON(value?: Families | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_embedded': FamiliesEmbeddedToJSON(value.embedded),
        '_links': ProductsLinksToJSON(value.links),
        'current_page': value.currentPage,
    };
}

