/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetAssetFamilyCode200ResponseTransformationsInnerOperations } from './GetAssetFamilyCode200ResponseTransformationsInnerOperations';
import {
    GetAssetFamilyCode200ResponseTransformationsInnerOperationsFromJSON,
    GetAssetFamilyCode200ResponseTransformationsInnerOperationsFromJSONTyped,
    GetAssetFamilyCode200ResponseTransformationsInnerOperationsToJSON,
} from './GetAssetFamilyCode200ResponseTransformationsInnerOperations';
import type { GetAssetFamilyCode200ResponseTransformationsInnerSource } from './GetAssetFamilyCode200ResponseTransformationsInnerSource';
import {
    GetAssetFamilyCode200ResponseTransformationsInnerSourceFromJSON,
    GetAssetFamilyCode200ResponseTransformationsInnerSourceFromJSONTyped,
    GetAssetFamilyCode200ResponseTransformationsInnerSourceToJSON,
} from './GetAssetFamilyCode200ResponseTransformationsInnerSource';
import type { GetAssetFamilyCode200ResponseTransformationsInnerTarget } from './GetAssetFamilyCode200ResponseTransformationsInnerTarget';
import {
    GetAssetFamilyCode200ResponseTransformationsInnerTargetFromJSON,
    GetAssetFamilyCode200ResponseTransformationsInnerTargetFromJSONTyped,
    GetAssetFamilyCode200ResponseTransformationsInnerTargetToJSON,
} from './GetAssetFamilyCode200ResponseTransformationsInnerTarget';

/**
 * 
 * @export
 * @interface GetAssetFamilyCode200ResponseTransformationsInner
 */
export interface GetAssetFamilyCode200ResponseTransformationsInner {
    /**
     * The name of the transformation
     * @type {string}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInner
     */
    label: string;
    /**
     * The suffix that will be appended to the source filename to generate the target filename. More details <a href='/concepts/asset-manager.html#target-filename'>here</a>.
     * @type {string}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInner
     */
    filenameSuffix?: string;
    /**
     * The prefix that will be prepended to the source filename to generate the target filename. More details <a href='/concepts/asset-manager.html#target-filename'>here</a>.
     * @type {string}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInner
     */
    filenamePrefix?: string;
    /**
     * 
     * @type {GetAssetFamilyCode200ResponseTransformationsInnerSource}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInner
     */
    source: GetAssetFamilyCode200ResponseTransformationsInnerSource;
    /**
     * 
     * @type {GetAssetFamilyCode200ResponseTransformationsInnerTarget}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInner
     */
    target: GetAssetFamilyCode200ResponseTransformationsInnerTarget;
    /**
     * 
     * @type {GetAssetFamilyCode200ResponseTransformationsInnerOperations}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInner
     */
    operations: GetAssetFamilyCode200ResponseTransformationsInnerOperations;
}

/**
 * Check if a given object implements the GetAssetFamilyCode200ResponseTransformationsInner interface.
 */
export function instanceOfGetAssetFamilyCode200ResponseTransformationsInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "label" in value;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "target" in value;
    isInstance = isInstance && "operations" in value;

    return isInstance;
}

export function GetAssetFamilyCode200ResponseTransformationsInnerFromJSON(json: any): GetAssetFamilyCode200ResponseTransformationsInner {
    return GetAssetFamilyCode200ResponseTransformationsInnerFromJSONTyped(json, false);
}

export function GetAssetFamilyCode200ResponseTransformationsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAssetFamilyCode200ResponseTransformationsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'label': json['label'],
        'filenameSuffix': !exists(json, 'filename_suffix') ? undefined : json['filename_suffix'],
        'filenamePrefix': !exists(json, 'filename_prefix') ? undefined : json['filename_prefix'],
        'source': GetAssetFamilyCode200ResponseTransformationsInnerSourceFromJSON(json['source']),
        'target': GetAssetFamilyCode200ResponseTransformationsInnerTargetFromJSON(json['target']),
        'operations': GetAssetFamilyCode200ResponseTransformationsInnerOperationsFromJSON(json['operations']),
    };
}

export function GetAssetFamilyCode200ResponseTransformationsInnerToJSON(value?: GetAssetFamilyCode200ResponseTransformationsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'label': value.label,
        'filename_suffix': value.filenameSuffix,
        'filename_prefix': value.filenamePrefix,
        'source': GetAssetFamilyCode200ResponseTransformationsInnerSourceToJSON(value.source),
        'target': GetAssetFamilyCode200ResponseTransformationsInnerTargetToJSON(value.target),
        'operations': GetAssetFamilyCode200ResponseTransformationsInnerOperationsToJSON(value.operations),
    };
}

