/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetAssetFamilyCode200ResponseLabels } from './GetAssetFamilyCode200ResponseLabels';
import {
    GetAssetFamilyCode200ResponseLabelsFromJSON,
    GetAssetFamilyCode200ResponseLabelsFromJSONTyped,
    GetAssetFamilyCode200ResponseLabelsToJSON,
} from './GetAssetFamilyCode200ResponseLabels';
import type { GetAssetFamilyCode200ResponseNamingConvention } from './GetAssetFamilyCode200ResponseNamingConvention';
import {
    GetAssetFamilyCode200ResponseNamingConventionFromJSON,
    GetAssetFamilyCode200ResponseNamingConventionFromJSONTyped,
    GetAssetFamilyCode200ResponseNamingConventionToJSON,
} from './GetAssetFamilyCode200ResponseNamingConvention';
import type { GetAssetFamilyCode200ResponseProductLinkRulesInner } from './GetAssetFamilyCode200ResponseProductLinkRulesInner';
import {
    GetAssetFamilyCode200ResponseProductLinkRulesInnerFromJSON,
    GetAssetFamilyCode200ResponseProductLinkRulesInnerFromJSONTyped,
    GetAssetFamilyCode200ResponseProductLinkRulesInnerToJSON,
} from './GetAssetFamilyCode200ResponseProductLinkRulesInner';
import type { GetAssetFamilyCode200ResponseTransformationsInner } from './GetAssetFamilyCode200ResponseTransformationsInner';
import {
    GetAssetFamilyCode200ResponseTransformationsInnerFromJSON,
    GetAssetFamilyCode200ResponseTransformationsInnerFromJSONTyped,
    GetAssetFamilyCode200ResponseTransformationsInnerToJSON,
} from './GetAssetFamilyCode200ResponseTransformationsInner';

/**
 * 
 * @export
 * @interface GetAssetFamilyCode200Response
 */
export interface GetAssetFamilyCode200Response {
    /**
     * Asset family code
     * @type {string}
     * @memberof GetAssetFamilyCode200Response
     */
    code: string;
    /**
     * 
     * @type {GetAssetFamilyCode200ResponseLabels}
     * @memberof GetAssetFamilyCode200Response
     */
    labels?: GetAssetFamilyCode200ResponseLabels;
    /**
     * Attribute code that is used as the main media of the asset family.
     * @type {string}
     * @memberof GetAssetFamilyCode200Response
     */
    attributeAsMainMedia?: string;
    /**
     * 
     * @type {GetAssetFamilyCode200ResponseNamingConvention}
     * @memberof GetAssetFamilyCode200Response
     */
    namingConvention?: GetAssetFamilyCode200ResponseNamingConvention;
    /**
     * The rules that will be run after the asset creation, in order to automatically link the assets of this family to a set of products. To understand the format of this property, see <a href='/concepts/asset-manager.html#focus-on-the-product-link-rule'>here</a>.
     * @type {Array<GetAssetFamilyCode200ResponseProductLinkRulesInner>}
     * @memberof GetAssetFamilyCode200Response
     */
    productLinkRules?: Array<GetAssetFamilyCode200ResponseProductLinkRulesInner>;
    /**
     * The transformations to perform on source files in order to generate new files into your asset attributes (only available since v4.0). To understand the format of this property, see <a href='/concepts/asset-manager.html#focus-on-the-transformations'>here</a>.
     * @type {Array<GetAssetFamilyCode200ResponseTransformationsInner>}
     * @memberof GetAssetFamilyCode200Response
     */
    transformations?: Array<GetAssetFamilyCode200ResponseTransformationsInner>;
}

/**
 * Check if a given object implements the GetAssetFamilyCode200Response interface.
 */
export function instanceOfGetAssetFamilyCode200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function GetAssetFamilyCode200ResponseFromJSON(json: any): GetAssetFamilyCode200Response {
    return GetAssetFamilyCode200ResponseFromJSONTyped(json, false);
}

export function GetAssetFamilyCode200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAssetFamilyCode200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'labels': !exists(json, 'labels') ? undefined : GetAssetFamilyCode200ResponseLabelsFromJSON(json['labels']),
        'attributeAsMainMedia': !exists(json, 'attribute_as_main_media') ? undefined : json['attribute_as_main_media'],
        'namingConvention': !exists(json, 'naming_convention') ? undefined : GetAssetFamilyCode200ResponseNamingConventionFromJSON(json['naming_convention']),
        'productLinkRules': !exists(json, 'product_link_rules') ? undefined : ((json['product_link_rules'] as Array<any>).map(GetAssetFamilyCode200ResponseProductLinkRulesInnerFromJSON)),
        'transformations': !exists(json, 'transformations') ? undefined : ((json['transformations'] as Array<any>).map(GetAssetFamilyCode200ResponseTransformationsInnerFromJSON)),
    };
}

export function GetAssetFamilyCode200ResponseToJSON(value?: GetAssetFamilyCode200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'labels': GetAssetFamilyCode200ResponseLabelsToJSON(value.labels),
        'attribute_as_main_media': value.attributeAsMainMedia,
        'naming_convention': GetAssetFamilyCode200ResponseNamingConventionToJSON(value.namingConvention),
        'product_link_rules': value.productLinkRules === undefined ? undefined : ((value.productLinkRules as Array<any>).map(GetAssetFamilyCode200ResponseProductLinkRulesInnerToJSON)),
        'transformations': value.transformations === undefined ? undefined : ((value.transformations as Array<any>).map(GetAssetFamilyCode200ResponseTransformationsInnerToJSON)),
    };
}

