/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters
 */
export interface GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters {
    /**
     * 
     * @type {string}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters
     */
    colorspace?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters
     */
    height?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters
     */
    ratio?: number;
    /**
     * 
     * @type {string}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters
     */
    resolutionUnit?: string;
    /**
     * 
     * @type {number}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters
     */
    resolutionX?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters
     */
    resolutionY?: number;
    /**
     * 
     * @type {number}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters
     */
    quality?: number;
}

/**
 * Check if a given object implements the GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters interface.
 */
export function instanceOfGetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAssetFamilyCode200ResponseTransformationsInnerOperationsParametersFromJSON(json: any): GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters {
    return GetAssetFamilyCode200ResponseTransformationsInnerOperationsParametersFromJSONTyped(json, false);
}

export function GetAssetFamilyCode200ResponseTransformationsInnerOperationsParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'colorspace': !exists(json, 'colorspace') ? undefined : json['colorspace'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'ratio': !exists(json, 'ratio') ? undefined : json['ratio'],
        'resolutionUnit': !exists(json, 'resolution-unit') ? undefined : json['resolution-unit'],
        'resolutionX': !exists(json, 'resolution-x') ? undefined : json['resolution-x'],
        'resolutionY': !exists(json, 'resolution-y') ? undefined : json['resolution-y'],
        'quality': !exists(json, 'quality') ? undefined : json['quality'],
    };
}

export function GetAssetFamilyCode200ResponseTransformationsInnerOperationsParametersToJSON(value?: GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'colorspace': value.colorspace,
        'width': value.width,
        'height': value.height,
        'ratio': value.ratio,
        'resolution-unit': value.resolutionUnit,
        'resolution-x': value.resolutionX,
        'resolution-y': value.resolutionY,
        'quality': value.quality,
    };
}

