/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters } from './GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters';
import {
    GetAssetFamilyCode200ResponseTransformationsInnerOperationsParametersFromJSON,
    GetAssetFamilyCode200ResponseTransformationsInnerOperationsParametersFromJSONTyped,
    GetAssetFamilyCode200ResponseTransformationsInnerOperationsParametersToJSON,
} from './GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters';

/**
 * The transformations that should be applied to your source file to generate the target file. More details <a href='/concepts/asset-manager.html#transformation-operations'>here</a>.
 * @export
 * @interface GetAssetFamilyCode200ResponseTransformationsInnerOperations
 */
export interface GetAssetFamilyCode200ResponseTransformationsInnerOperations {
    /**
     * 
     * @type {string}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInnerOperations
     */
    type?: string;
    /**
     * 
     * @type {GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters}
     * @memberof GetAssetFamilyCode200ResponseTransformationsInnerOperations
     */
    parameters?: GetAssetFamilyCode200ResponseTransformationsInnerOperationsParameters;
}

/**
 * Check if a given object implements the GetAssetFamilyCode200ResponseTransformationsInnerOperations interface.
 */
export function instanceOfGetAssetFamilyCode200ResponseTransformationsInnerOperations(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAssetFamilyCode200ResponseTransformationsInnerOperationsFromJSON(json: any): GetAssetFamilyCode200ResponseTransformationsInnerOperations {
    return GetAssetFamilyCode200ResponseTransformationsInnerOperationsFromJSONTyped(json, false);
}

export function GetAssetFamilyCode200ResponseTransformationsInnerOperationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAssetFamilyCode200ResponseTransformationsInnerOperations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'parameters': !exists(json, 'parameters') ? undefined : GetAssetFamilyCode200ResponseTransformationsInnerOperationsParametersFromJSON(json['parameters']),
    };
}

export function GetAssetFamilyCode200ResponseTransformationsInnerOperationsToJSON(value?: GetAssetFamilyCode200ResponseTransformationsInnerOperations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'parameters': GetAssetFamilyCode200ResponseTransformationsInnerOperationsParametersToJSON(value.parameters),
    };
}

