/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLocalesCode200Response
 */
export interface GetLocalesCode200Response {
    /**
     * Locale code
     * @type {string}
     * @memberof GetLocalesCode200Response
     */
    code: string;
    /**
     * Whether the locale is enabled
     * @type {boolean}
     * @memberof GetLocalesCode200Response
     */
    enabled?: boolean;
}

/**
 * Check if a given object implements the GetLocalesCode200Response interface.
 */
export function instanceOfGetLocalesCode200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function GetLocalesCode200ResponseFromJSON(json: any): GetLocalesCode200Response {
    return GetLocalesCode200ResponseFromJSONTyped(json, false);
}

export function GetLocalesCode200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLocalesCode200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
    };
}

export function GetLocalesCode200ResponseToJSON(value?: GetLocalesCode200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'enabled': value.enabled,
    };
}

