/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetMediaFilesCode200ResponseLinksDownload
 */
export interface GetMediaFilesCode200ResponseLinksDownload {
    /**
     * URI to download the binaries of the media file
     * @type {string}
     * @memberof GetMediaFilesCode200ResponseLinksDownload
     */
    href?: string;
}

/**
 * Check if a given object implements the GetMediaFilesCode200ResponseLinksDownload interface.
 */
export function instanceOfGetMediaFilesCode200ResponseLinksDownload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetMediaFilesCode200ResponseLinksDownloadFromJSON(json: any): GetMediaFilesCode200ResponseLinksDownload {
    return GetMediaFilesCode200ResponseLinksDownloadFromJSONTyped(json, false);
}

export function GetMediaFilesCode200ResponseLinksDownloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMediaFilesCode200ResponseLinksDownload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
    };
}

export function GetMediaFilesCode200ResponseLinksDownloadToJSON(value?: GetMediaFilesCode200ResponseLinksDownload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
    };
}

