/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MediaFilesEmbeddedItemsInnerAllOfLinksDownload } from './MediaFilesEmbeddedItemsInnerAllOfLinksDownload';
import {
    MediaFilesEmbeddedItemsInnerAllOfLinksDownloadFromJSON,
    MediaFilesEmbeddedItemsInnerAllOfLinksDownloadFromJSONTyped,
    MediaFilesEmbeddedItemsInnerAllOfLinksDownloadToJSON,
} from './MediaFilesEmbeddedItemsInnerAllOfLinksDownload';

/**
 * 
 * @export
 * @interface GetMediaFilesCode200ResponseLinks
 */
export interface GetMediaFilesCode200ResponseLinks {
    /**
     * 
     * @type {MediaFilesEmbeddedItemsInnerAllOfLinksDownload}
     * @memberof GetMediaFilesCode200ResponseLinks
     */
    download?: MediaFilesEmbeddedItemsInnerAllOfLinksDownload;
}

/**
 * Check if a given object implements the GetMediaFilesCode200ResponseLinks interface.
 */
export function instanceOfGetMediaFilesCode200ResponseLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetMediaFilesCode200ResponseLinksFromJSON(json: any): GetMediaFilesCode200ResponseLinks {
    return GetMediaFilesCode200ResponseLinksFromJSONTyped(json, false);
}

export function GetMediaFilesCode200ResponseLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMediaFilesCode200ResponseLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'download': !exists(json, 'download') ? undefined : MediaFilesEmbeddedItemsInnerAllOfLinksDownloadFromJSON(json['download']),
    };
}

export function GetMediaFilesCode200ResponseLinksToJSON(value?: GetMediaFilesCode200ResponseLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'download': MediaFilesEmbeddedItemsInnerAllOfLinksDownloadToJSON(value.download),
    };
}

