/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetReferenceEntitiesCode200ResponseLinksImageDownload
 */
export interface GetReferenceEntitiesCode200ResponseLinksImageDownload {
    /**
     * URI to download the binaries of the reference entity image file
     * @type {string}
     * @memberof GetReferenceEntitiesCode200ResponseLinksImageDownload
     */
    href?: string;
}

/**
 * Check if a given object implements the GetReferenceEntitiesCode200ResponseLinksImageDownload interface.
 */
export function instanceOfGetReferenceEntitiesCode200ResponseLinksImageDownload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetReferenceEntitiesCode200ResponseLinksImageDownloadFromJSON(json: any): GetReferenceEntitiesCode200ResponseLinksImageDownload {
    return GetReferenceEntitiesCode200ResponseLinksImageDownloadFromJSONTyped(json, false);
}

export function GetReferenceEntitiesCode200ResponseLinksImageDownloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetReferenceEntitiesCode200ResponseLinksImageDownload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
    };
}

export function GetReferenceEntitiesCode200ResponseLinksImageDownloadToJSON(value?: GetReferenceEntitiesCode200ResponseLinksImageDownload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
    };
}

