/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetReferenceEntitiesCode200ResponseLinksImageDownload } from './GetReferenceEntitiesCode200ResponseLinksImageDownload';
import {
    GetReferenceEntitiesCode200ResponseLinksImageDownloadFromJSON,
    GetReferenceEntitiesCode200ResponseLinksImageDownloadFromJSONTyped,
    GetReferenceEntitiesCode200ResponseLinksImageDownloadToJSON,
} from './GetReferenceEntitiesCode200ResponseLinksImageDownload';

/**
 * 
 * @export
 * @interface GetReferenceEntitiesCode200ResponseLinks
 */
export interface GetReferenceEntitiesCode200ResponseLinks {
    /**
     * 
     * @type {GetReferenceEntitiesCode200ResponseLinksImageDownload}
     * @memberof GetReferenceEntitiesCode200ResponseLinks
     */
    imageDownload?: GetReferenceEntitiesCode200ResponseLinksImageDownload;
}

/**
 * Check if a given object implements the GetReferenceEntitiesCode200ResponseLinks interface.
 */
export function instanceOfGetReferenceEntitiesCode200ResponseLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetReferenceEntitiesCode200ResponseLinksFromJSON(json: any): GetReferenceEntitiesCode200ResponseLinks {
    return GetReferenceEntitiesCode200ResponseLinksFromJSONTyped(json, false);
}

export function GetReferenceEntitiesCode200ResponseLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetReferenceEntitiesCode200ResponseLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageDownload': !exists(json, 'image_download') ? undefined : GetReferenceEntitiesCode200ResponseLinksImageDownloadFromJSON(json['image_download']),
    };
}

export function GetReferenceEntitiesCode200ResponseLinksToJSON(value?: GetReferenceEntitiesCode200ResponseLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image_download': GetReferenceEntitiesCode200ResponseLinksImageDownloadToJSON(value.imageDownload),
    };
}

