/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MeasureFamiliesEmbedded } from './MeasureFamiliesEmbedded';
import {
    MeasureFamiliesEmbeddedFromJSON,
    MeasureFamiliesEmbeddedFromJSONTyped,
    MeasureFamiliesEmbeddedToJSON,
} from './MeasureFamiliesEmbedded';
import type { ProductsLinks } from './ProductsLinks';
import {
    ProductsLinksFromJSON,
    ProductsLinksFromJSONTyped,
    ProductsLinksToJSON,
} from './ProductsLinks';

/**
 * 
 * @export
 * @interface MeasureFamilies
 */
export interface MeasureFamilies {
    /**
     * 
     * @type {MeasureFamiliesEmbedded}
     * @memberof MeasureFamilies
     */
    embedded?: MeasureFamiliesEmbedded;
    /**
     * 
     * @type {ProductsLinks}
     * @memberof MeasureFamilies
     */
    links?: ProductsLinks;
    /**
     * Current page number
     * @type {number}
     * @memberof MeasureFamilies
     */
    currentPage?: number;
}

/**
 * Check if a given object implements the MeasureFamilies interface.
 */
export function instanceOfMeasureFamilies(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MeasureFamiliesFromJSON(json: any): MeasureFamilies {
    return MeasureFamiliesFromJSONTyped(json, false);
}

export function MeasureFamiliesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasureFamilies {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'embedded': !exists(json, '_embedded') ? undefined : MeasureFamiliesEmbeddedFromJSON(json['_embedded']),
        'links': !exists(json, '_links') ? undefined : ProductsLinksFromJSON(json['_links']),
        'currentPage': !exists(json, 'current_page') ? undefined : json['current_page'],
    };
}

export function MeasureFamiliesToJSON(value?: MeasureFamilies | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_embedded': MeasureFamiliesEmbeddedToJSON(value.embedded),
        '_links': ProductsLinksToJSON(value.links),
        'current_page': value.currentPage,
    };
}

