/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MeasureFamiliesEmbeddedItemsInnerAllOfUnitsInner } from './MeasureFamiliesEmbeddedItemsInnerAllOfUnitsInner';
import {
    MeasureFamiliesEmbeddedItemsInnerAllOfUnitsInnerFromJSON,
    MeasureFamiliesEmbeddedItemsInnerAllOfUnitsInnerFromJSONTyped,
    MeasureFamiliesEmbeddedItemsInnerAllOfUnitsInnerToJSON,
} from './MeasureFamiliesEmbeddedItemsInnerAllOfUnitsInner';

/**
 * 
 * @export
 * @interface MeasureFamiliesEmbeddedItemsInnerAllOf
 */
export interface MeasureFamiliesEmbeddedItemsInnerAllOf {
    /**
     * Measure family code
     * @type {string}
     * @memberof MeasureFamiliesEmbeddedItemsInnerAllOf
     */
    code: string;
    /**
     * Measure family standard
     * @type {string}
     * @memberof MeasureFamiliesEmbeddedItemsInnerAllOf
     */
    standard?: string;
    /**
     * Family units
     * @type {Array<MeasureFamiliesEmbeddedItemsInnerAllOfUnitsInner>}
     * @memberof MeasureFamiliesEmbeddedItemsInnerAllOf
     */
    units?: Array<MeasureFamiliesEmbeddedItemsInnerAllOfUnitsInner>;
}

/**
 * Check if a given object implements the MeasureFamiliesEmbeddedItemsInnerAllOf interface.
 */
export function instanceOfMeasureFamiliesEmbeddedItemsInnerAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function MeasureFamiliesEmbeddedItemsInnerAllOfFromJSON(json: any): MeasureFamiliesEmbeddedItemsInnerAllOf {
    return MeasureFamiliesEmbeddedItemsInnerAllOfFromJSONTyped(json, false);
}

export function MeasureFamiliesEmbeddedItemsInnerAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasureFamiliesEmbeddedItemsInnerAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'standard': !exists(json, 'standard') ? undefined : json['standard'],
        'units': !exists(json, 'units') ? undefined : ((json['units'] as Array<any>).map(MeasureFamiliesEmbeddedItemsInnerAllOfUnitsInnerFromJSON)),
    };
}

export function MeasureFamiliesEmbeddedItemsInnerAllOfToJSON(value?: MeasureFamiliesEmbeddedItemsInnerAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'standard': value.standard,
        'units': value.units === undefined ? undefined : ((value.units as Array<any>).map(MeasureFamiliesEmbeddedItemsInnerAllOfUnitsInnerToJSON)),
    };
}

