/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MediaFilesEmbeddedItemsInnerAllOfLinksDownload } from './MediaFilesEmbeddedItemsInnerAllOfLinksDownload';
import {
    MediaFilesEmbeddedItemsInnerAllOfLinksDownloadFromJSON,
    MediaFilesEmbeddedItemsInnerAllOfLinksDownloadFromJSONTyped,
    MediaFilesEmbeddedItemsInnerAllOfLinksDownloadToJSON,
} from './MediaFilesEmbeddedItemsInnerAllOfLinksDownload';
import type { MediaFilesEmbeddedItemsInnerAllOfLinksSelf } from './MediaFilesEmbeddedItemsInnerAllOfLinksSelf';
import {
    MediaFilesEmbeddedItemsInnerAllOfLinksSelfFromJSON,
    MediaFilesEmbeddedItemsInnerAllOfLinksSelfFromJSONTyped,
    MediaFilesEmbeddedItemsInnerAllOfLinksSelfToJSON,
} from './MediaFilesEmbeddedItemsInnerAllOfLinksSelf';

/**
 * 
 * @export
 * @interface MediaFilesEmbeddedItemsInnerAllOfLinks
 */
export interface MediaFilesEmbeddedItemsInnerAllOfLinks {
    /**
     * 
     * @type {MediaFilesEmbeddedItemsInnerAllOfLinksSelf}
     * @memberof MediaFilesEmbeddedItemsInnerAllOfLinks
     */
    self?: MediaFilesEmbeddedItemsInnerAllOfLinksSelf;
    /**
     * 
     * @type {MediaFilesEmbeddedItemsInnerAllOfLinksDownload}
     * @memberof MediaFilesEmbeddedItemsInnerAllOfLinks
     */
    download?: MediaFilesEmbeddedItemsInnerAllOfLinksDownload;
}

/**
 * Check if a given object implements the MediaFilesEmbeddedItemsInnerAllOfLinks interface.
 */
export function instanceOfMediaFilesEmbeddedItemsInnerAllOfLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MediaFilesEmbeddedItemsInnerAllOfLinksFromJSON(json: any): MediaFilesEmbeddedItemsInnerAllOfLinks {
    return MediaFilesEmbeddedItemsInnerAllOfLinksFromJSONTyped(json, false);
}

export function MediaFilesEmbeddedItemsInnerAllOfLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaFilesEmbeddedItemsInnerAllOfLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': !exists(json, 'self') ? undefined : MediaFilesEmbeddedItemsInnerAllOfLinksSelfFromJSON(json['self']),
        'download': !exists(json, 'download') ? undefined : MediaFilesEmbeddedItemsInnerAllOfLinksDownloadFromJSON(json['download']),
    };
}

export function MediaFilesEmbeddedItemsInnerAllOfLinksToJSON(value?: MediaFilesEmbeddedItemsInnerAllOfLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': MediaFilesEmbeddedItemsInnerAllOfLinksSelfToJSON(value.self),
        'download': MediaFilesEmbeddedItemsInnerAllOfLinksDownloadToJSON(value.download),
    };
}

