/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MediaFilesEmbeddedItemsInnerAllOfLinks } from './MediaFilesEmbeddedItemsInnerAllOfLinks';
import {
    MediaFilesEmbeddedItemsInnerAllOfLinksFromJSON,
    MediaFilesEmbeddedItemsInnerAllOfLinksFromJSONTyped,
    MediaFilesEmbeddedItemsInnerAllOfLinksToJSON,
} from './MediaFilesEmbeddedItemsInnerAllOfLinks';

/**
 * 
 * @export
 * @interface MediaFileItemList
 */
export interface MediaFileItemList {
    /**
     * 
     * @type {MediaFilesEmbeddedItemsInnerAllOfLinks}
     * @memberof MediaFileItemList
     */
    links?: MediaFilesEmbeddedItemsInnerAllOfLinks;
}

/**
 * Check if a given object implements the MediaFileItemList interface.
 */
export function instanceOfMediaFileItemList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MediaFileItemListFromJSON(json: any): MediaFileItemList {
    return MediaFileItemListFromJSONTyped(json, false);
}

export function MediaFileItemListFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaFileItemList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, '_links') ? undefined : MediaFilesEmbeddedItemsInnerAllOfLinksFromJSON(json['_links']),
    };
}

export function MediaFileItemListToJSON(value?: MediaFileItemList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_links': MediaFilesEmbeddedItemsInnerAllOfLinksToJSON(value.links),
    };
}

