/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MediaFilesEmbeddedItemsInner } from './MediaFilesEmbeddedItemsInner';
import {
    MediaFilesEmbeddedItemsInnerFromJSON,
    MediaFilesEmbeddedItemsInnerFromJSONTyped,
    MediaFilesEmbeddedItemsInnerToJSON,
} from './MediaFilesEmbeddedItemsInner';

/**
 * 
 * @export
 * @interface MediaFilesEmbedded
 */
export interface MediaFilesEmbedded {
    /**
     * 
     * @type {Array<MediaFilesEmbeddedItemsInner>}
     * @memberof MediaFilesEmbedded
     */
    items?: Array<MediaFilesEmbeddedItemsInner>;
}

/**
 * Check if a given object implements the MediaFilesEmbedded interface.
 */
export function instanceOfMediaFilesEmbedded(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MediaFilesEmbeddedFromJSON(json: any): MediaFilesEmbedded {
    return MediaFilesEmbeddedFromJSONTyped(json, false);
}

export function MediaFilesEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaFilesEmbedded {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(MediaFilesEmbeddedItemsInnerFromJSON)),
    };
}

export function MediaFilesEmbeddedToJSON(value?: MediaFilesEmbedded | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(MediaFilesEmbeddedItemsInnerToJSON)),
    };
}

