/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MediaFileAllOfLinks } from './MediaFileAllOfLinks';
import {
    MediaFileAllOfLinksFromJSON,
    MediaFileAllOfLinksFromJSONTyped,
    MediaFileAllOfLinksToJSON,
} from './MediaFileAllOfLinks';

/**
 * 
 * @export
 * @interface MediaFile
 */
export interface MediaFile {
    /**
     * 
     * @type {MediaFileAllOfLinks}
     * @memberof MediaFile
     */
    links?: MediaFileAllOfLinks;
    /**
     * Media file code
     * @type {string}
     * @memberof MediaFile
     */
    code?: string;
    /**
     * Original filename of the media file
     * @type {string}
     * @memberof MediaFile
     */
    originalFilename?: string;
    /**
     * Mime type of the media file
     * @type {string}
     * @memberof MediaFile
     */
    mimeType?: string;
    /**
     * Size of the media file
     * @type {number}
     * @memberof MediaFile
     */
    size?: number;
    /**
     * Extension of the media file
     * @type {string}
     * @memberof MediaFile
     */
    extension?: string;
}

/**
 * Check if a given object implements the MediaFile interface.
 */
export function instanceOfMediaFile(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MediaFileFromJSON(json: any): MediaFile {
    return MediaFileFromJSONTyped(json, false);
}

export function MediaFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): MediaFile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, '_links') ? undefined : MediaFileAllOfLinksFromJSON(json['_links']),
        'code': !exists(json, 'code') ? undefined : json['code'],
        'originalFilename': !exists(json, 'original_filename') ? undefined : json['original_filename'],
        'mimeType': !exists(json, 'mime_type') ? undefined : json['mime_type'],
        'size': !exists(json, 'size') ? undefined : json['size'],
        'extension': !exists(json, 'extension') ? undefined : json['extension'],
    };
}

export function MediaFileToJSON(value?: MediaFile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_links': MediaFileAllOfLinksToJSON(value.links),
        'code': value.code,
        'original_filename': value.originalFilename,
        'mime_type': value.mimeType,
        'size': value.size,
        'extension': value.extension,
    };
}

