/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerLink } from './PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerLink';
import {
    PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerLinkFromJSON,
    PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerLinkFromJSONTyped,
    PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerLinkToJSON,
} from './PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerLink';

/**
 * 
 * @export
 * @interface PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner
 */
export interface PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner {
    /**
     * 
     * @type {PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerLink}
     * @memberof PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner
     */
    link?: PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerLink;
    /**
     * Locale code of the variation
     * @type {string}
     * @memberof PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner
     */
    locale?: string;
    /**
     * Channel code of the variation
     * @type {string}
     * @memberof PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner
     */
    scope?: string;
    /**
     * Code of the variation
     * @type {string}
     * @memberof PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner
     */
    code?: string;
}

/**
 * Check if a given object implements the PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner interface.
 */
export function instanceOfPAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerFromJSON(json: any): PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner {
    return PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerFromJSONTyped(json, false);
}

export function PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'link': !exists(json, '_link') ? undefined : PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerLinkFromJSON(json['_link']),
        'locale': !exists(json, 'locale') ? undefined : json['locale'],
        'scope': !exists(json, 'scope') ? undefined : json['scope'],
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerToJSON(value?: PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_link': PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerLinkToJSON(value.link),
        'locale': value.locale,
        'scope': value.scope,
        'code': value.code,
    };
}

