/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkDownload } from './PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkDownload';
import {
    PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkDownloadFromJSON,
    PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkDownloadFromJSONTyped,
    PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkDownloadToJSON,
} from './PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkDownload';
import type { PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkSelf } from './PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkSelf';
import {
    PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkSelfFromJSON,
    PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkSelfFromJSONTyped,
    PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkSelfToJSON,
} from './PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkSelf';

/**
 * Links to get and download the reference file
 * @export
 * @interface PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLink
 */
export interface PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLink {
    /**
     * 
     * @type {PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkSelf}
     * @memberof PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLink
     */
    self?: PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkSelf;
    /**
     * 
     * @type {PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkDownload}
     * @memberof PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLink
     */
    download?: PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkDownload;
}

/**
 * Check if a given object implements the PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLink interface.
 */
export function instanceOfPAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLink(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkFromJSON(json: any): PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLink {
    return PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkFromJSONTyped(json, false);
}

export function PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': !exists(json, 'self') ? undefined : PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkSelfFromJSON(json['self']),
        'download': !exists(json, 'download') ? undefined : PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkDownloadFromJSON(json['download']),
    };
}

export function PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkToJSON(value?: PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkSelfToJSON(value.self),
        'download': PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerLinkDownloadToJSON(value.download),
    };
}

