/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GetReferenceEntitiesCode200ResponseLabels } from './GetReferenceEntitiesCode200ResponseLabels';
import {
    GetReferenceEntitiesCode200ResponseLabelsFromJSON,
    GetReferenceEntitiesCode200ResponseLabelsFromJSONTyped,
    GetReferenceEntitiesCode200ResponseLabelsToJSON,
} from './GetReferenceEntitiesCode200ResponseLabels';

/**
 * 
 * @export
 * @interface PatchReferenceEntityCodeRequest
 */
export interface PatchReferenceEntityCodeRequest {
    /**
     * Reference entity code
     * @type {string}
     * @memberof PatchReferenceEntityCodeRequest
     */
    code: string;
    /**
     * 
     * @type {GetReferenceEntitiesCode200ResponseLabels}
     * @memberof PatchReferenceEntityCodeRequest
     */
    labels?: GetReferenceEntitiesCode200ResponseLabels;
    /**
     * Code of the reference entity image
     * @type {string}
     * @memberof PatchReferenceEntityCodeRequest
     */
    image?: string;
}

/**
 * Check if a given object implements the PatchReferenceEntityCodeRequest interface.
 */
export function instanceOfPatchReferenceEntityCodeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function PatchReferenceEntityCodeRequestFromJSON(json: any): PatchReferenceEntityCodeRequest {
    return PatchReferenceEntityCodeRequestFromJSONTyped(json, false);
}

export function PatchReferenceEntityCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchReferenceEntityCodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'labels': !exists(json, 'labels') ? undefined : GetReferenceEntitiesCode200ResponseLabelsFromJSON(json['labels']),
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function PatchReferenceEntityCodeRequestToJSON(value?: PatchReferenceEntityCodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'labels': GetReferenceEntitiesCode200ResponseLabelsToJSON(value.labels),
        'image': value.image,
    };
}

