/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssetFamiliesEmbeddedItemsInnerAllOfLabels } from './AssetFamiliesEmbeddedItemsInnerAllOfLabels';
import {
    AssetFamiliesEmbeddedItemsInnerAllOfLabelsFromJSON,
    AssetFamiliesEmbeddedItemsInnerAllOfLabelsFromJSONTyped,
    AssetFamiliesEmbeddedItemsInnerAllOfLabelsToJSON,
} from './AssetFamiliesEmbeddedItemsInnerAllOfLabels';
import type { AssetFamiliesEmbeddedItemsInnerAllOfNamingConvention } from './AssetFamiliesEmbeddedItemsInnerAllOfNamingConvention';
import {
    AssetFamiliesEmbeddedItemsInnerAllOfNamingConventionFromJSON,
    AssetFamiliesEmbeddedItemsInnerAllOfNamingConventionFromJSONTyped,
    AssetFamiliesEmbeddedItemsInnerAllOfNamingConventionToJSON,
} from './AssetFamiliesEmbeddedItemsInnerAllOfNamingConvention';
import type { AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInner } from './AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInner';
import {
    AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerFromJSON,
    AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerFromJSONTyped,
    AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerToJSON,
} from './AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInner';
import type { AssetFamiliesEmbeddedItemsInnerAllOfTransformationsInner } from './AssetFamiliesEmbeddedItemsInnerAllOfTransformationsInner';
import {
    AssetFamiliesEmbeddedItemsInnerAllOfTransformationsInnerFromJSON,
    AssetFamiliesEmbeddedItemsInnerAllOfTransformationsInnerFromJSONTyped,
    AssetFamiliesEmbeddedItemsInnerAllOfTransformationsInnerToJSON,
} from './AssetFamiliesEmbeddedItemsInnerAllOfTransformationsInner';

/**
 * 
 * @export
 * @interface PatchAssetFamilyCodeRequest
 */
export interface PatchAssetFamilyCodeRequest {
    /**
     * Asset family code
     * @type {string}
     * @memberof PatchAssetFamilyCodeRequest
     */
    code: string;
    /**
     * 
     * @type {AssetFamiliesEmbeddedItemsInnerAllOfLabels}
     * @memberof PatchAssetFamilyCodeRequest
     */
    labels?: AssetFamiliesEmbeddedItemsInnerAllOfLabels;
    /**
     * Attribute code that is used as the main media of the asset family.
     * @type {string}
     * @memberof PatchAssetFamilyCodeRequest
     */
    attributeAsMainMedia?: string;
    /**
     * 
     * @type {AssetFamiliesEmbeddedItemsInnerAllOfNamingConvention}
     * @memberof PatchAssetFamilyCodeRequest
     */
    namingConvention?: AssetFamiliesEmbeddedItemsInnerAllOfNamingConvention;
    /**
     * The rules that will be run after the asset creation, in order to automatically link the assets of this family to a set of products. To understand the format of this property, see <a href='/concepts/asset-manager.html#focus-on-the-product-link-rule'>here</a>.
     * @type {Array<AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInner>}
     * @memberof PatchAssetFamilyCodeRequest
     */
    productLinkRules?: Array<AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInner>;
    /**
     * The transformations to perform on source files in order to generate new files into your asset attributes (only available since v4.0). To understand the format of this property, see <a href='/concepts/asset-manager.html#focus-on-the-transformations'>here</a>.
     * @type {Array<AssetFamiliesEmbeddedItemsInnerAllOfTransformationsInner>}
     * @memberof PatchAssetFamilyCodeRequest
     */
    transformations?: Array<AssetFamiliesEmbeddedItemsInnerAllOfTransformationsInner>;
}

/**
 * Check if a given object implements the PatchAssetFamilyCodeRequest interface.
 */
export function instanceOfPatchAssetFamilyCodeRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function PatchAssetFamilyCodeRequestFromJSON(json: any): PatchAssetFamilyCodeRequest {
    return PatchAssetFamilyCodeRequestFromJSONTyped(json, false);
}

export function PatchAssetFamilyCodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchAssetFamilyCodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'labels': !exists(json, 'labels') ? undefined : AssetFamiliesEmbeddedItemsInnerAllOfLabelsFromJSON(json['labels']),
        'attributeAsMainMedia': !exists(json, 'attribute_as_main_media') ? undefined : json['attribute_as_main_media'],
        'namingConvention': !exists(json, 'naming_convention') ? undefined : AssetFamiliesEmbeddedItemsInnerAllOfNamingConventionFromJSON(json['naming_convention']),
        'productLinkRules': !exists(json, 'product_link_rules') ? undefined : ((json['product_link_rules'] as Array<any>).map(AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerFromJSON)),
        'transformations': !exists(json, 'transformations') ? undefined : ((json['transformations'] as Array<any>).map(AssetFamiliesEmbeddedItemsInnerAllOfTransformationsInnerFromJSON)),
    };
}

export function PatchAssetFamilyCodeRequestToJSON(value?: PatchAssetFamilyCodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'labels': AssetFamiliesEmbeddedItemsInnerAllOfLabelsToJSON(value.labels),
        'attribute_as_main_media': value.attributeAsMainMedia,
        'naming_convention': AssetFamiliesEmbeddedItemsInnerAllOfNamingConventionToJSON(value.namingConvention),
        'product_link_rules': value.productLinkRules === undefined ? undefined : ((value.productLinkRules as Array<any>).map(AssetFamiliesEmbeddedItemsInnerAllOfProductLinkRulesInnerToJSON)),
        'transformations': value.transformations === undefined ? undefined : ((value.transformations as Array<any>).map(AssetFamiliesEmbeddedItemsInnerAllOfTransformationsInnerToJSON)),
    };
}

