/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchProductsUuid200Response
 */
export interface PatchProductsUuid200Response {
    /**
     * Line number
     * @type {number}
     * @memberof PatchProductsUuid200Response
     */
    line?: number;
    /**
     * Product uuid
     * @type {string}
     * @memberof PatchProductsUuid200Response
     */
    uuid?: string;
    /**
     * HTTP status code, see <a href="/documentation/responses.html#client-errors">Client errors</a> to understand the meaning of each code
     * @type {number}
     * @memberof PatchProductsUuid200Response
     */
    statusCode?: number;
    /**
     * Message explaining the error
     * @type {string}
     * @memberof PatchProductsUuid200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the PatchProductsUuid200Response interface.
 */
export function instanceOfPatchProductsUuid200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchProductsUuid200ResponseFromJSON(json: any): PatchProductsUuid200Response {
    return PatchProductsUuid200ResponseFromJSONTyped(json, false);
}

export function PatchProductsUuid200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchProductsUuid200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'line': !exists(json, 'line') ? undefined : json['line'],
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'statusCode': !exists(json, 'status_code') ? undefined : json['status_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function PatchProductsUuid200ResponseToJSON(value?: PatchProductsUuid200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'line': value.line,
        'uuid': value.uuid,
        'status_code': value.statusCode,
        'message': value.message,
    };
}

