/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostPamAssetsRequestReferenceFilesInnerLink } from './PostPamAssetsRequestReferenceFilesInnerLink';
import {
    PostPamAssetsRequestReferenceFilesInnerLinkFromJSON,
    PostPamAssetsRequestReferenceFilesInnerLinkFromJSONTyped,
    PostPamAssetsRequestReferenceFilesInnerLinkToJSON,
} from './PostPamAssetsRequestReferenceFilesInnerLink';

/**
 * 
 * @export
 * @interface PostPamAssetsRequestReferenceFilesInner
 */
export interface PostPamAssetsRequestReferenceFilesInner {
    /**
     * 
     * @type {PostPamAssetsRequestReferenceFilesInnerLink}
     * @memberof PostPamAssetsRequestReferenceFilesInner
     */
    link?: PostPamAssetsRequestReferenceFilesInnerLink;
    /**
     * Locale code of the reference file
     * @type {string}
     * @memberof PostPamAssetsRequestReferenceFilesInner
     */
    locale?: string;
    /**
     * Code of the reference file
     * @type {string}
     * @memberof PostPamAssetsRequestReferenceFilesInner
     */
    code?: string;
}

/**
 * Check if a given object implements the PostPamAssetsRequestReferenceFilesInner interface.
 */
export function instanceOfPostPamAssetsRequestReferenceFilesInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostPamAssetsRequestReferenceFilesInnerFromJSON(json: any): PostPamAssetsRequestReferenceFilesInner {
    return PostPamAssetsRequestReferenceFilesInnerFromJSONTyped(json, false);
}

export function PostPamAssetsRequestReferenceFilesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPamAssetsRequestReferenceFilesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'link': !exists(json, '_link') ? undefined : PostPamAssetsRequestReferenceFilesInnerLinkFromJSON(json['_link']),
        'locale': !exists(json, 'locale') ? undefined : json['locale'],
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function PostPamAssetsRequestReferenceFilesInnerToJSON(value?: PostPamAssetsRequestReferenceFilesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_link': PostPamAssetsRequestReferenceFilesInnerLinkToJSON(value.link),
        'locale': value.locale,
        'code': value.code,
    };
}

