/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostProductsRequestCompletenessesInner } from './PostProductsRequestCompletenessesInner';
import {
    PostProductsRequestCompletenessesInnerFromJSON,
    PostProductsRequestCompletenessesInnerFromJSONTyped,
    PostProductsRequestCompletenessesInnerToJSON,
} from './PostProductsRequestCompletenessesInner';
import type { PostProductsRequestMetadata } from './PostProductsRequestMetadata';
import {
    PostProductsRequestMetadataFromJSON,
    PostProductsRequestMetadataFromJSONTyped,
    PostProductsRequestMetadataToJSON,
} from './PostProductsRequestMetadata';
import type { PostProductsRequestValues } from './PostProductsRequestValues';
import {
    PostProductsRequestValuesFromJSON,
    PostProductsRequestValuesFromJSONTyped,
    PostProductsRequestValuesToJSON,
} from './PostProductsRequestValues';
import type { PostProductsUuidRequestAssociations } from './PostProductsUuidRequestAssociations';
import {
    PostProductsUuidRequestAssociationsFromJSON,
    PostProductsUuidRequestAssociationsFromJSONTyped,
    PostProductsUuidRequestAssociationsToJSON,
} from './PostProductsUuidRequestAssociations';
import type { PostProductsUuidRequestQuantifiedAssociations } from './PostProductsUuidRequestQuantifiedAssociations';
import {
    PostProductsUuidRequestQuantifiedAssociationsFromJSON,
    PostProductsUuidRequestQuantifiedAssociationsFromJSONTyped,
    PostProductsUuidRequestQuantifiedAssociationsToJSON,
} from './PostProductsUuidRequestQuantifiedAssociations';

/**
 * 
 * @export
 * @interface PostProductsUuidRequest
 */
export interface PostProductsUuidRequest {
    /**
     * Product uuid
     * @type {string}
     * @memberof PostProductsUuidRequest
     */
    uuid?: string;
    /**
     * Whether the product is enabled
     * @type {boolean}
     * @memberof PostProductsUuidRequest
     */
    enabled?: boolean;
    /**
     * <a href='api-reference.html#Family'>Family</a> code from which the product inherits its attributes and attributes requirements.
     * @type {string}
     * @memberof PostProductsUuidRequest
     */
    family?: string;
    /**
     * Codes of the <a href='api-reference.html#Category'>categories</a> in which the product is classified
     * @type {Array<string>}
     * @memberof PostProductsUuidRequest
     */
    categories?: Array<string>;
    /**
     * Codes of the groups to which the product belong
     * @type {Array<string>}
     * @memberof PostProductsUuidRequest
     */
    groups?: Array<string>;
    /**
     * Code of the parent <a href='api-reference.html#Productmodel'>product model</a> when the product is a variant (only available since the 2.0). This parent can be modified since the 2.3.
     * @type {string}
     * @memberof PostProductsUuidRequest
     */
    parent?: string;
    /**
     * 
     * @type {PostProductsRequestValues}
     * @memberof PostProductsUuidRequest
     */
    values?: PostProductsRequestValues;
    /**
     * 
     * @type {PostProductsUuidRequestAssociations}
     * @memberof PostProductsUuidRequest
     */
    associations?: PostProductsUuidRequestAssociations;
    /**
     * 
     * @type {PostProductsUuidRequestQuantifiedAssociations}
     * @memberof PostProductsUuidRequest
     */
    quantifiedAssociations?: PostProductsUuidRequestQuantifiedAssociations;
    /**
     * Date of creation
     * @type {string}
     * @memberof PostProductsUuidRequest
     */
    created?: string;
    /**
     * Date of the last update
     * @type {string}
     * @memberof PostProductsUuidRequest
     */
    updated?: string;
    /**
     * 
     * @type {PostProductsRequestMetadata}
     * @memberof PostProductsUuidRequest
     */
    metadata?: PostProductsRequestMetadata;
    /**
     * Product quality scores for each channel/locale combination (only available since the 5.0 and when the "with_quality_scores" query parameter is set to "true")
     * @type {object}
     * @memberof PostProductsUuidRequest
     */
    qualityScores?: object;
    /**
     * Product completenesses for each channel/locale combination (only available on SaaS platforms, and when the "with_completenesses" query parameter is set to "true")
     * @type {Array<PostProductsRequestCompletenessesInner>}
     * @memberof PostProductsUuidRequest
     */
    completenesses?: Array<PostProductsRequestCompletenessesInner>;
}

/**
 * Check if a given object implements the PostProductsUuidRequest interface.
 */
export function instanceOfPostProductsUuidRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostProductsUuidRequestFromJSON(json: any): PostProductsUuidRequest {
    return PostProductsUuidRequestFromJSONTyped(json, false);
}

export function PostProductsUuidRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostProductsUuidRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'enabled': !exists(json, 'enabled') ? undefined : json['enabled'],
        'family': !exists(json, 'family') ? undefined : json['family'],
        'categories': !exists(json, 'categories') ? undefined : json['categories'],
        'groups': !exists(json, 'groups') ? undefined : json['groups'],
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
        'values': !exists(json, 'values') ? undefined : PostProductsRequestValuesFromJSON(json['values']),
        'associations': !exists(json, 'associations') ? undefined : PostProductsUuidRequestAssociationsFromJSON(json['associations']),
        'quantifiedAssociations': !exists(json, 'quantified_associations') ? undefined : PostProductsUuidRequestQuantifiedAssociationsFromJSON(json['quantified_associations']),
        'created': !exists(json, 'created') ? undefined : json['created'],
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
        'metadata': !exists(json, 'metadata') ? undefined : PostProductsRequestMetadataFromJSON(json['metadata']),
        'qualityScores': !exists(json, 'quality_scores') ? undefined : json['quality_scores'],
        'completenesses': !exists(json, 'completenesses') ? undefined : ((json['completenesses'] as Array<any>).map(PostProductsRequestCompletenessesInnerFromJSON)),
    };
}

export function PostProductsUuidRequestToJSON(value?: PostProductsUuidRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'enabled': value.enabled,
        'family': value.family,
        'categories': value.categories,
        'groups': value.groups,
        'parent': value.parent,
        'values': PostProductsRequestValuesToJSON(value.values),
        'associations': PostProductsUuidRequestAssociationsToJSON(value.associations),
        'quantified_associations': PostProductsUuidRequestQuantifiedAssociationsToJSON(value.quantifiedAssociations),
        'created': value.created,
        'updated': value.updated,
        'metadata': PostProductsRequestMetadataToJSON(value.metadata),
        'quality_scores': value.qualityScores,
        'completenesses': value.completenesses === undefined ? undefined : ((value.completenesses as Array<any>).map(PostProductsRequestCompletenessesInnerToJSON)),
    };
}

