/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Column labels for each locale
 * @export
 * @interface PostAttributesRequestTableConfigurationInnerLabels
 */
export interface PostAttributesRequestTableConfigurationInnerLabels {
    /**
     * Column label for the locale `localeCode`
     * @type {string}
     * @memberof PostAttributesRequestTableConfigurationInnerLabels
     */
    localeCode?: string;
}

/**
 * Check if a given object implements the PostAttributesRequestTableConfigurationInnerLabels interface.
 */
export function instanceOfPostAttributesRequestTableConfigurationInnerLabels(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostAttributesRequestTableConfigurationInnerLabelsFromJSON(json: any): PostAttributesRequestTableConfigurationInnerLabels {
    return PostAttributesRequestTableConfigurationInnerLabelsFromJSONTyped(json, false);
}

export function PostAttributesRequestTableConfigurationInnerLabelsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostAttributesRequestTableConfigurationInnerLabels {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'localeCode': !exists(json, 'localeCode') ? undefined : json['localeCode'],
    };
}

export function PostAttributesRequestTableConfigurationInnerLabelsToJSON(value?: PostAttributesRequestTableConfigurationInnerLabels | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'localeCode': value.localeCode,
    };
}

