/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostPamAssetsRequestVariationFilesInnerLinkDownload
 */
export interface PostPamAssetsRequestVariationFilesInnerLinkDownload {
    /**
     * URI to download the variation file
     * @type {string}
     * @memberof PostPamAssetsRequestVariationFilesInnerLinkDownload
     */
    href?: string;
}

/**
 * Check if a given object implements the PostPamAssetsRequestVariationFilesInnerLinkDownload interface.
 */
export function instanceOfPostPamAssetsRequestVariationFilesInnerLinkDownload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostPamAssetsRequestVariationFilesInnerLinkDownloadFromJSON(json: any): PostPamAssetsRequestVariationFilesInnerLinkDownload {
    return PostPamAssetsRequestVariationFilesInnerLinkDownloadFromJSONTyped(json, false);
}

export function PostPamAssetsRequestVariationFilesInnerLinkDownloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPamAssetsRequestVariationFilesInnerLinkDownload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
    };
}

export function PostPamAssetsRequestVariationFilesInnerLinkDownloadToJSON(value?: PostPamAssetsRequestVariationFilesInnerLinkDownload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
    };
}

