/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInner } from './PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInner';
import {
    PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerFromJSON,
    PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerFromJSONTyped,
    PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerToJSON,
} from './PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInner';
import type { PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner } from './PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner';
import {
    PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerFromJSON,
    PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerFromJSONTyped,
    PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerToJSON,
} from './PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner';

/**
 * 
 * @export
 * @interface PostPamAssetsRequest
 */
export interface PostPamAssetsRequest {
    /**
     * PAM asset code
     * @type {string}
     * @memberof PostPamAssetsRequest
     */
    code: string;
    /**
     * Codes of the PAM asset categories in which the asset is classified
     * @type {Array<string>}
     * @memberof PostPamAssetsRequest
     */
    categories?: Array<string>;
    /**
     * Description of the PAM asset
     * @type {string}
     * @memberof PostPamAssetsRequest
     */
    description?: string;
    /**
     * Whether the asset is localized or not, meaning if you want to have different reference files for each of your locale
     * @type {boolean}
     * @memberof PostPamAssetsRequest
     */
    localizable?: boolean;
    /**
     * Tags of the PAM asset
     * @type {Array<string>}
     * @memberof PostPamAssetsRequest
     */
    tags?: Array<string>;
    /**
     * Date on which the PAM asset expire
     * @type {string}
     * @memberof PostPamAssetsRequest
     */
    endOfUse?: string;
    /**
     * Variations of the PAM asset
     * @type {Array<PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner>}
     * @memberof PostPamAssetsRequest
     */
    variationFiles?: Array<PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInner>;
    /**
     * Reference files of the PAM asset
     * @type {Array<PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInner>}
     * @memberof PostPamAssetsRequest
     */
    referenceFiles?: Array<PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInner>;
}

/**
 * Check if a given object implements the PostPamAssetsRequest interface.
 */
export function instanceOfPostPamAssetsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function PostPamAssetsRequestFromJSON(json: any): PostPamAssetsRequest {
    return PostPamAssetsRequestFromJSONTyped(json, false);
}

export function PostPamAssetsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPamAssetsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'categories': !exists(json, 'categories') ? undefined : json['categories'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'localizable': !exists(json, 'localizable') ? undefined : json['localizable'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'endOfUse': !exists(json, 'end_of_use') ? undefined : json['end_of_use'],
        'variationFiles': !exists(json, 'variation_files') ? undefined : ((json['variation_files'] as Array<any>).map(PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerFromJSON)),
        'referenceFiles': !exists(json, 'reference_files') ? undefined : ((json['reference_files'] as Array<any>).map(PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerFromJSON)),
    };
}

export function PostPamAssetsRequestToJSON(value?: PostPamAssetsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'categories': value.categories,
        'description': value.description,
        'localizable': value.localizable,
        'tags': value.tags,
        'end_of_use': value.endOfUse,
        'variation_files': value.variationFiles === undefined ? undefined : ((value.variationFiles as Array<any>).map(PAMAssetsEmbeddedItemsInnerAllOfVariationFilesInnerToJSON)),
        'reference_files': value.referenceFiles === undefined ? undefined : ((value.referenceFiles as Array<any>).map(PAMAssetsEmbeddedItemsInnerAllOfReferenceFilesInnerToJSON)),
    };
}

