/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostProductsUuidRequestQuantifiedAssociationsQuantifiedAssociationTypeCode } from './PostProductsUuidRequestQuantifiedAssociationsQuantifiedAssociationTypeCode';
import {
    PostProductsUuidRequestQuantifiedAssociationsQuantifiedAssociationTypeCodeFromJSON,
    PostProductsUuidRequestQuantifiedAssociationsQuantifiedAssociationTypeCodeFromJSONTyped,
    PostProductsUuidRequestQuantifiedAssociationsQuantifiedAssociationTypeCodeToJSON,
} from './PostProductsUuidRequestQuantifiedAssociationsQuantifiedAssociationTypeCode';

/**
 * Several quantified associations related to products and/or product models, grouped by quantified association types (only available since the 5.0)
 * @export
 * @interface PostProductsUuidRequestQuantifiedAssociations
 */
export interface PostProductsUuidRequestQuantifiedAssociations {
    /**
     * 
     * @type {PostProductsUuidRequestQuantifiedAssociationsQuantifiedAssociationTypeCode}
     * @memberof PostProductsUuidRequestQuantifiedAssociations
     */
    quantifiedAssociationTypeCode?: PostProductsUuidRequestQuantifiedAssociationsQuantifiedAssociationTypeCode;
}

/**
 * Check if a given object implements the PostProductsUuidRequestQuantifiedAssociations interface.
 */
export function instanceOfPostProductsUuidRequestQuantifiedAssociations(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostProductsUuidRequestQuantifiedAssociationsFromJSON(json: any): PostProductsUuidRequestQuantifiedAssociations {
    return PostProductsUuidRequestQuantifiedAssociationsFromJSONTyped(json, false);
}

export function PostProductsUuidRequestQuantifiedAssociationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostProductsUuidRequestQuantifiedAssociations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quantifiedAssociationTypeCode': !exists(json, 'quantifiedAssociationTypeCode') ? undefined : PostProductsUuidRequestQuantifiedAssociationsQuantifiedAssociationTypeCodeFromJSON(json['quantifiedAssociationTypeCode']),
    };
}

export function PostProductsUuidRequestQuantifiedAssociationsToJSON(value?: PostProductsUuidRequestQuantifiedAssociations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quantifiedAssociationTypeCode': PostProductsUuidRequestQuantifiedAssociationsQuantifiedAssociationTypeCodeToJSON(value.quantifiedAssociationTypeCode),
    };
}

