/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PostPamAssetsRequestReferenceFilesInnerLinkDownload } from './PostPamAssetsRequestReferenceFilesInnerLinkDownload';
import {
    PostPamAssetsRequestReferenceFilesInnerLinkDownloadFromJSON,
    PostPamAssetsRequestReferenceFilesInnerLinkDownloadFromJSONTyped,
    PostPamAssetsRequestReferenceFilesInnerLinkDownloadToJSON,
} from './PostPamAssetsRequestReferenceFilesInnerLinkDownload';
import type { PostPamAssetsRequestReferenceFilesInnerLinkSelf } from './PostPamAssetsRequestReferenceFilesInnerLinkSelf';
import {
    PostPamAssetsRequestReferenceFilesInnerLinkSelfFromJSON,
    PostPamAssetsRequestReferenceFilesInnerLinkSelfFromJSONTyped,
    PostPamAssetsRequestReferenceFilesInnerLinkSelfToJSON,
} from './PostPamAssetsRequestReferenceFilesInnerLinkSelf';

/**
 * Links to get and download the reference file
 * @export
 * @interface PostPamAssetsRequestReferenceFilesInnerLink
 */
export interface PostPamAssetsRequestReferenceFilesInnerLink {
    /**
     * 
     * @type {PostPamAssetsRequestReferenceFilesInnerLinkSelf}
     * @memberof PostPamAssetsRequestReferenceFilesInnerLink
     */
    self?: PostPamAssetsRequestReferenceFilesInnerLinkSelf;
    /**
     * 
     * @type {PostPamAssetsRequestReferenceFilesInnerLinkDownload}
     * @memberof PostPamAssetsRequestReferenceFilesInnerLink
     */
    download?: PostPamAssetsRequestReferenceFilesInnerLinkDownload;
}

/**
 * Check if a given object implements the PostPamAssetsRequestReferenceFilesInnerLink interface.
 */
export function instanceOfPostPamAssetsRequestReferenceFilesInnerLink(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostPamAssetsRequestReferenceFilesInnerLinkFromJSON(json: any): PostPamAssetsRequestReferenceFilesInnerLink {
    return PostPamAssetsRequestReferenceFilesInnerLinkFromJSONTyped(json, false);
}

export function PostPamAssetsRequestReferenceFilesInnerLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostPamAssetsRequestReferenceFilesInnerLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': !exists(json, 'self') ? undefined : PostPamAssetsRequestReferenceFilesInnerLinkSelfFromJSON(json['self']),
        'download': !exists(json, 'download') ? undefined : PostPamAssetsRequestReferenceFilesInnerLinkDownloadFromJSON(json['download']),
    };
}

export function PostPamAssetsRequestReferenceFilesInnerLinkToJSON(value?: PostPamAssetsRequestReferenceFilesInnerLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': PostPamAssetsRequestReferenceFilesInnerLinkSelfToJSON(value.self),
        'download': PostPamAssetsRequestReferenceFilesInnerLinkDownloadToJSON(value.download),
    };
}

