/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CategoriesEmbeddedItemsInnerAllOfLabels } from './CategoriesEmbeddedItemsInnerAllOfLabels';
import {
    CategoriesEmbeddedItemsInnerAllOfLabelsFromJSON,
    CategoriesEmbeddedItemsInnerAllOfLabelsFromJSONTyped,
    CategoriesEmbeddedItemsInnerAllOfLabelsToJSON,
} from './CategoriesEmbeddedItemsInnerAllOfLabels';
import type { CategoriesEmbeddedItemsInnerAllOfValues } from './CategoriesEmbeddedItemsInnerAllOfValues';
import {
    CategoriesEmbeddedItemsInnerAllOfValuesFromJSON,
    CategoriesEmbeddedItemsInnerAllOfValuesFromJSONTyped,
    CategoriesEmbeddedItemsInnerAllOfValuesToJSON,
} from './CategoriesEmbeddedItemsInnerAllOfValues';

/**
 * 
 * @export
 * @interface PostCategoriesRequest
 */
export interface PostCategoriesRequest {
    /**
     * Category code
     * @type {string}
     * @memberof PostCategoriesRequest
     */
    code: string;
    /**
     * Category code of the parent's category
     * @type {string}
     * @memberof PostCategoriesRequest
     */
    parent?: string;
    /**
     * Date of the last update
     * @type {string}
     * @memberof PostCategoriesRequest
     */
    updated?: string;
    /**
     * Position of the category in its level, start from 1 (only available since the 7.0 version and when query parameter "with_position" is set to "true")
     * @type {number}
     * @memberof PostCategoriesRequest
     */
    position?: number;
    /**
     * 
     * @type {CategoriesEmbeddedItemsInnerAllOfLabels}
     * @memberof PostCategoriesRequest
     */
    labels?: CategoriesEmbeddedItemsInnerAllOfLabels;
    /**
     * 
     * @type {CategoriesEmbeddedItemsInnerAllOfValues}
     * @memberof PostCategoriesRequest
     */
    values?: CategoriesEmbeddedItemsInnerAllOfValues;
}

/**
 * Check if a given object implements the PostCategoriesRequest interface.
 */
export function instanceOfPostCategoriesRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function PostCategoriesRequestFromJSON(json: any): PostCategoriesRequest {
    return PostCategoriesRequestFromJSONTyped(json, false);
}

export function PostCategoriesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostCategoriesRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'parent': !exists(json, 'parent') ? undefined : json['parent'],
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
        'position': !exists(json, 'position') ? undefined : json['position'],
        'labels': !exists(json, 'labels') ? undefined : CategoriesEmbeddedItemsInnerAllOfLabelsFromJSON(json['labels']),
        'values': !exists(json, 'values') ? undefined : CategoriesEmbeddedItemsInnerAllOfValuesFromJSON(json['values']),
    };
}

export function PostCategoriesRequestToJSON(value?: PostCategoriesRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'parent': value.parent,
        'updated': value.updated,
        'position': value.position,
        'labels': CategoriesEmbeddedItemsInnerAllOfLabelsToJSON(value.labels),
        'values': CategoriesEmbeddedItemsInnerAllOfValuesToJSON(value.values),
    };
}

