/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Object containing labels of attribute options (only available since the 5.0 and when query parameter "with_attribute_options" is set to "true"). See <a href='/concepts/products.html#the-linked_data-format'>the `linked_data` format</a> section for more details.
 * @export
 * @interface PostProductsRequestValuesAttributeCodeInnerLinkedData
 */
export interface PostProductsRequestValuesAttributeCodeInnerLinkedData {
    /**
     * 
     * @type {string}
     * @memberof PostProductsRequestValuesAttributeCodeInnerLinkedData
     */
    attribute?: string;
    /**
     * 
     * @type {string}
     * @memberof PostProductsRequestValuesAttributeCodeInnerLinkedData
     */
    code?: string;
    /**
     * 
     * @type {object}
     * @memberof PostProductsRequestValuesAttributeCodeInnerLinkedData
     */
    labels?: object;
}

/**
 * Check if a given object implements the PostProductsRequestValuesAttributeCodeInnerLinkedData interface.
 */
export function instanceOfPostProductsRequestValuesAttributeCodeInnerLinkedData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PostProductsRequestValuesAttributeCodeInnerLinkedDataFromJSON(json: any): PostProductsRequestValuesAttributeCodeInnerLinkedData {
    return PostProductsRequestValuesAttributeCodeInnerLinkedDataFromJSONTyped(json, false);
}

export function PostProductsRequestValuesAttributeCodeInnerLinkedDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostProductsRequestValuesAttributeCodeInnerLinkedData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attribute': !exists(json, 'attribute') ? undefined : json['attribute'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'labels': !exists(json, 'labels') ? undefined : json['labels'],
    };
}

export function PostProductsRequestValuesAttributeCodeInnerLinkedDataToJSON(value?: PostProductsRequestValuesAttributeCodeInnerLinkedData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attribute': value.attribute,
        'code': value.code,
        'labels': value.labels,
    };
}

