/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductsLinksFirst
 */
export interface ProductsLinksFirst {
    /**
     * URI of the first page of resources
     * @type {string}
     * @memberof ProductsLinksFirst
     */
    href?: string;
}

/**
 * Check if a given object implements the ProductsLinksFirst interface.
 */
export function instanceOfProductsLinksFirst(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductsLinksFirstFromJSON(json: any): ProductsLinksFirst {
    return ProductsLinksFirstFromJSONTyped(json, false);
}

export function ProductsLinksFirstFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsLinksFirst {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
    };
}

export function ProductsLinksFirstToJSON(value?: ProductsLinksFirst | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
    };
}

