/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerLinkedData } from './ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerLinkedData';
import {
    ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerLinkedDataFromJSON,
    ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerLinkedDataFromJSONTyped,
    ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerLinkedDataToJSON,
} from './ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerLinkedData';

/**
 * 
 * @export
 * @interface ProductsEmbeddedItemsInnerAllOf1ValuesValueInner
 */
export interface ProductsEmbeddedItemsInnerAllOf1ValuesValueInner {
    /**
     * <a href='api-reference.html#Channel'>Channel</a> code of the product value
     * @type {string}
     * @memberof ProductsEmbeddedItemsInnerAllOf1ValuesValueInner
     */
    scope?: string;
    /**
     * <a href='api-reference.html#Locale'>Locale</a> code of the product value
     * @type {string}
     * @memberof ProductsEmbeddedItemsInnerAllOf1ValuesValueInner
     */
    locale?: string;
    /**
     * Product value. See <a href='/concepts/products.html#the-data-format'>the `data` format</a> section for more details.
     * @type {object}
     * @memberof ProductsEmbeddedItemsInnerAllOf1ValuesValueInner
     */
    data?: object;
    /**
     * 
     * @type {ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerLinkedData}
     * @memberof ProductsEmbeddedItemsInnerAllOf1ValuesValueInner
     */
    linkedData?: ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerLinkedData;
}

/**
 * Check if a given object implements the ProductsEmbeddedItemsInnerAllOf1ValuesValueInner interface.
 */
export function instanceOfProductsEmbeddedItemsInnerAllOf1ValuesValueInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerFromJSON(json: any): ProductsEmbeddedItemsInnerAllOf1ValuesValueInner {
    return ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerFromJSONTyped(json, false);
}

export function ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsEmbeddedItemsInnerAllOf1ValuesValueInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'scope': !exists(json, 'scope') ? undefined : json['scope'],
        'locale': !exists(json, 'locale') ? undefined : json['locale'],
        'data': !exists(json, 'data') ? undefined : json['data'],
        'linkedData': !exists(json, 'linked_data') ? undefined : ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerLinkedDataFromJSON(json['linked_data']),
    };
}

export function ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerToJSON(value?: ProductsEmbeddedItemsInnerAllOf1ValuesValueInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'scope': value.scope,
        'locale': value.locale,
        'data': value.data,
        'linked_data': ProductsEmbeddedItemsInnerAllOf1ValuesValueInnerLinkedDataToJSON(value.linkedData),
    };
}

