/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductListAllOf1AssociationsAssociationTypeCode } from './ProductListAllOf1AssociationsAssociationTypeCode';
import {
    ProductListAllOf1AssociationsAssociationTypeCodeFromJSON,
    ProductListAllOf1AssociationsAssociationTypeCodeFromJSONTyped,
    ProductListAllOf1AssociationsAssociationTypeCodeToJSON,
} from './ProductListAllOf1AssociationsAssociationTypeCode';

/**
 * Several associations related to groups, product models and/or other products, grouped by association types
 * @export
 * @interface ProductListAllOf1Associations
 */
export interface ProductListAllOf1Associations {
    /**
     * 
     * @type {ProductListAllOf1AssociationsAssociationTypeCode}
     * @memberof ProductListAllOf1Associations
     */
    associationTypeCode?: ProductListAllOf1AssociationsAssociationTypeCode;
}

/**
 * Check if a given object implements the ProductListAllOf1Associations interface.
 */
export function instanceOfProductListAllOf1Associations(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductListAllOf1AssociationsFromJSON(json: any): ProductListAllOf1Associations {
    return ProductListAllOf1AssociationsFromJSONTyped(json, false);
}

export function ProductListAllOf1AssociationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductListAllOf1Associations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'associationTypeCode': !exists(json, 'associationTypeCode') ? undefined : ProductListAllOf1AssociationsAssociationTypeCodeFromJSON(json['associationTypeCode']),
    };
}

export function ProductListAllOf1AssociationsToJSON(value?: ProductListAllOf1Associations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'associationTypeCode': ProductListAllOf1AssociationsAssociationTypeCodeToJSON(value.associationTypeCode),
    };
}

