/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductsEmbeddedItemsInnerAllOfLinks } from './ProductsEmbeddedItemsInnerAllOfLinks';
import {
    ProductsEmbeddedItemsInnerAllOfLinksFromJSON,
    ProductsEmbeddedItemsInnerAllOfLinksFromJSONTyped,
    ProductsEmbeddedItemsInnerAllOfLinksToJSON,
} from './ProductsEmbeddedItemsInnerAllOfLinks';

/**
 * 
 * @export
 * @interface ProductsEmbeddedItemsInnerAllOf
 */
export interface ProductsEmbeddedItemsInnerAllOf {
    /**
     * 
     * @type {ProductsEmbeddedItemsInnerAllOfLinks}
     * @memberof ProductsEmbeddedItemsInnerAllOf
     */
    links?: ProductsEmbeddedItemsInnerAllOfLinks;
}

/**
 * Check if a given object implements the ProductsEmbeddedItemsInnerAllOf interface.
 */
export function instanceOfProductsEmbeddedItemsInnerAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductsEmbeddedItemsInnerAllOfFromJSON(json: any): ProductsEmbeddedItemsInnerAllOf {
    return ProductsEmbeddedItemsInnerAllOfFromJSONTyped(json, false);
}

export function ProductsEmbeddedItemsInnerAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsEmbeddedItemsInnerAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, '_links') ? undefined : ProductsEmbeddedItemsInnerAllOfLinksFromJSON(json['_links']),
    };
}

export function ProductsEmbeddedItemsInnerAllOfToJSON(value?: ProductsEmbeddedItemsInnerAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_links': ProductsEmbeddedItemsInnerAllOfLinksToJSON(value.links),
    };
}

