/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode } from './ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode';
import {
    ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeFromJSON,
    ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeFromJSONTyped,
    ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeToJSON,
} from './ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode';

/**
 * Several quantified associations related to products and/or product models, grouped by quantified association types (only available since the 5.0)
 * @export
 * @interface ProductUuidListAllOfQuantifiedAssociations
 */
export interface ProductUuidListAllOfQuantifiedAssociations {
    /**
     * 
     * @type {ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode}
     * @memberof ProductUuidListAllOfQuantifiedAssociations
     */
    quantifiedAssociationTypeCode?: ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCode;
}

/**
 * Check if a given object implements the ProductUuidListAllOfQuantifiedAssociations interface.
 */
export function instanceOfProductUuidListAllOfQuantifiedAssociations(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductUuidListAllOfQuantifiedAssociationsFromJSON(json: any): ProductUuidListAllOfQuantifiedAssociations {
    return ProductUuidListAllOfQuantifiedAssociationsFromJSONTyped(json, false);
}

export function ProductUuidListAllOfQuantifiedAssociationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUuidListAllOfQuantifiedAssociations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quantifiedAssociationTypeCode': !exists(json, 'quantifiedAssociationTypeCode') ? undefined : ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeFromJSON(json['quantifiedAssociationTypeCode']),
    };
}

export function ProductUuidListAllOfQuantifiedAssociationsToJSON(value?: ProductUuidListAllOfQuantifiedAssociations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quantifiedAssociationTypeCode': ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeToJSON(value.quantifiedAssociationTypeCode),
    };
}

