/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductsEmbeddedItemsInnerAllOfLinksSelf } from './ProductsEmbeddedItemsInnerAllOfLinksSelf';
import {
    ProductsEmbeddedItemsInnerAllOfLinksSelfFromJSON,
    ProductsEmbeddedItemsInnerAllOfLinksSelfFromJSONTyped,
    ProductsEmbeddedItemsInnerAllOfLinksSelfToJSON,
} from './ProductsEmbeddedItemsInnerAllOfLinksSelf';

/**
 * 
 * @export
 * @interface ProductsEmbeddedItemsInnerAllOfLinks
 */
export interface ProductsEmbeddedItemsInnerAllOfLinks {
    /**
     * 
     * @type {ProductsEmbeddedItemsInnerAllOfLinksSelf}
     * @memberof ProductsEmbeddedItemsInnerAllOfLinks
     */
    self?: ProductsEmbeddedItemsInnerAllOfLinksSelf;
}

/**
 * Check if a given object implements the ProductsEmbeddedItemsInnerAllOfLinks interface.
 */
export function instanceOfProductsEmbeddedItemsInnerAllOfLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductsEmbeddedItemsInnerAllOfLinksFromJSON(json: any): ProductsEmbeddedItemsInnerAllOfLinks {
    return ProductsEmbeddedItemsInnerAllOfLinksFromJSONTyped(json, false);
}

export function ProductsEmbeddedItemsInnerAllOfLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsEmbeddedItemsInnerAllOfLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': !exists(json, 'self') ? undefined : ProductsEmbeddedItemsInnerAllOfLinksSelfFromJSON(json['self']),
    };
}

export function ProductsEmbeddedItemsInnerAllOfLinksToJSON(value?: ProductsEmbeddedItemsInnerAllOfLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': ProductsEmbeddedItemsInnerAllOfLinksSelfToJSON(value.self),
    };
}

