/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductsLinksNext
 */
export interface ProductsLinksNext {
    /**
     * URI of the next page of resources
     * @type {string}
     * @memberof ProductsLinksNext
     */
    href?: string;
}

/**
 * Check if a given object implements the ProductsLinksNext interface.
 */
export function instanceOfProductsLinksNext(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductsLinksNextFromJSON(json: any): ProductsLinksNext {
    return ProductsLinksNextFromJSONTyped(json, false);
}

export function ProductsLinksNextFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsLinksNext {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
    };
}

export function ProductsLinksNextToJSON(value?: ProductsLinksNext | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
    };
}

