/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductListAllOf1ValuesAttributeCode } from './ProductListAllOf1ValuesAttributeCode';
import {
    ProductListAllOf1ValuesAttributeCodeFromJSON,
    ProductListAllOf1ValuesAttributeCodeFromJSONTyped,
    ProductListAllOf1ValuesAttributeCodeToJSON,
} from './ProductListAllOf1ValuesAttributeCode';

/**
 * Product attributes values, see <a href='/concepts/products.html#focus-on-the-product-values'>Product values</a> section for more details
 * @export
 * @interface ProductListAllOf1Values
 */
export interface ProductListAllOf1Values {
    /**
     * 
     * @type {Array<ProductListAllOf1ValuesAttributeCode>}
     * @memberof ProductListAllOf1Values
     */
    attributeCode?: Array<ProductListAllOf1ValuesAttributeCode>;
}

/**
 * Check if a given object implements the ProductListAllOf1Values interface.
 */
export function instanceOfProductListAllOf1Values(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductListAllOf1ValuesFromJSON(json: any): ProductListAllOf1Values {
    return ProductListAllOf1ValuesFromJSONTyped(json, false);
}

export function ProductListAllOf1ValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductListAllOf1Values {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributeCode': !exists(json, 'attributeCode') ? undefined : ((json['attributeCode'] as Array<any>).map(ProductListAllOf1ValuesAttributeCodeFromJSON)),
    };
}

export function ProductListAllOf1ValuesToJSON(value?: ProductListAllOf1Values | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributeCode': value.attributeCode === undefined ? undefined : ((value.attributeCode as Array<any>).map(ProductListAllOf1ValuesAttributeCodeToJSON)),
    };
}

