/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductsLinksSelf
 */
export interface ProductsLinksSelf {
    /**
     * URI of the current page of resources
     * @type {string}
     * @memberof ProductsLinksSelf
     */
    href?: string;
}

/**
 * Check if a given object implements the ProductsLinksSelf interface.
 */
export function instanceOfProductsLinksSelf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductsLinksSelfFromJSON(json: any): ProductsLinksSelf {
    return ProductsLinksSelfFromJSONTyped(json, false);
}

export function ProductsLinksSelfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsLinksSelf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
    };
}

export function ProductsLinksSelfToJSON(value?: ProductsLinksSelf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
    };
}

