/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts
 */
export interface ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts {
    /**
     * 
     * @type {string}
     * @memberof ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts
     */
    uuid?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts
     */
    quantity?: number;
}

/**
 * Check if a given object implements the ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts interface.
 */
export function instanceOfProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsFromJSON(json: any): ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts {
    return ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsFromJSONTyped(json, false);
}

export function ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uuid': !exists(json, 'uuid') ? undefined : json['uuid'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProductsToJSON(value?: ProductUuidListAllOfQuantifiedAssociationsQuantifiedAssociationTypeCodeProducts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uuid': value.uuid,
        'quantity': value.quantity,
    };
}

