/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductsEmbeddedItemsInner } from './ProductsEmbeddedItemsInner';
import {
    ProductsEmbeddedItemsInnerFromJSON,
    ProductsEmbeddedItemsInnerFromJSONTyped,
    ProductsEmbeddedItemsInnerToJSON,
} from './ProductsEmbeddedItemsInner';

/**
 * 
 * @export
 * @interface ProductsEmbedded
 */
export interface ProductsEmbedded {
    /**
     * 
     * @type {Array<ProductsEmbeddedItemsInner>}
     * @memberof ProductsEmbedded
     */
    items?: Array<ProductsEmbeddedItemsInner>;
}

/**
 * Check if a given object implements the ProductsEmbedded interface.
 */
export function instanceOfProductsEmbedded(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductsEmbeddedFromJSON(json: any): ProductsEmbedded {
    return ProductsEmbeddedFromJSONTyped(json, false);
}

export function ProductsEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductsEmbedded {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : ((json['items'] as Array<any>).map(ProductsEmbeddedItemsInnerFromJSON)),
    };
}

export function ProductsEmbeddedToJSON(value?: ProductsEmbedded | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : ((value.items as Array<any>).map(ProductsEmbeddedItemsInnerToJSON)),
    };
}

