/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AssetFamilyItemListLinksSelf } from './AssetFamilyItemListLinksSelf';
import {
    AssetFamilyItemListLinksSelfFromJSON,
    AssetFamilyItemListLinksSelfFromJSONTyped,
    AssetFamilyItemListLinksSelfToJSON,
} from './AssetFamilyItemListLinksSelf';
import type { GetReferenceEntitiesCode200ResponseLinksImageDownload } from './GetReferenceEntitiesCode200ResponseLinksImageDownload';
import {
    GetReferenceEntitiesCode200ResponseLinksImageDownloadFromJSON,
    GetReferenceEntitiesCode200ResponseLinksImageDownloadFromJSONTyped,
    GetReferenceEntitiesCode200ResponseLinksImageDownloadToJSON,
} from './GetReferenceEntitiesCode200ResponseLinksImageDownload';

/**
 * 
 * @export
 * @interface ReferenceEntityItemListLinks
 */
export interface ReferenceEntityItemListLinks {
    /**
     * 
     * @type {AssetFamilyItemListLinksSelf}
     * @memberof ReferenceEntityItemListLinks
     */
    self?: AssetFamilyItemListLinksSelf;
    /**
     * 
     * @type {GetReferenceEntitiesCode200ResponseLinksImageDownload}
     * @memberof ReferenceEntityItemListLinks
     */
    imageDownload?: GetReferenceEntitiesCode200ResponseLinksImageDownload;
}

/**
 * Check if a given object implements the ReferenceEntityItemListLinks interface.
 */
export function instanceOfReferenceEntityItemListLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferenceEntityItemListLinksFromJSON(json: any): ReferenceEntityItemListLinks {
    return ReferenceEntityItemListLinksFromJSONTyped(json, false);
}

export function ReferenceEntityItemListLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntityItemListLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': !exists(json, 'self') ? undefined : AssetFamilyItemListLinksSelfFromJSON(json['self']),
        'imageDownload': !exists(json, 'image_download') ? undefined : GetReferenceEntitiesCode200ResponseLinksImageDownloadFromJSON(json['image_download']),
    };
}

export function ReferenceEntityItemListLinksToJSON(value?: ReferenceEntityItemListLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': AssetFamilyItemListLinksSelfToJSON(value.self),
        'image_download': GetReferenceEntitiesCode200ResponseLinksImageDownloadToJSON(value.imageDownload),
    };
}

