/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceEntityAllOfLinksImageDownload } from './ReferenceEntityAllOfLinksImageDownload';
import {
    ReferenceEntityAllOfLinksImageDownloadFromJSON,
    ReferenceEntityAllOfLinksImageDownloadFromJSONTyped,
    ReferenceEntityAllOfLinksImageDownloadToJSON,
} from './ReferenceEntityAllOfLinksImageDownload';

/**
 * 
 * @export
 * @interface ReferenceEntityAllOfLinks
 */
export interface ReferenceEntityAllOfLinks {
    /**
     * 
     * @type {ReferenceEntityAllOfLinksImageDownload}
     * @memberof ReferenceEntityAllOfLinks
     */
    imageDownload?: ReferenceEntityAllOfLinksImageDownload;
}

/**
 * Check if a given object implements the ReferenceEntityAllOfLinks interface.
 */
export function instanceOfReferenceEntityAllOfLinks(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferenceEntityAllOfLinksFromJSON(json: any): ReferenceEntityAllOfLinks {
    return ReferenceEntityAllOfLinksFromJSONTyped(json, false);
}

export function ReferenceEntityAllOfLinksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntityAllOfLinks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'imageDownload': !exists(json, 'image_download') ? undefined : ReferenceEntityAllOfLinksImageDownloadFromJSON(json['image_download']),
    };
}

export function ReferenceEntityAllOfLinksToJSON(value?: ReferenceEntityAllOfLinks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image_download': ReferenceEntityAllOfLinksImageDownloadToJSON(value.imageDownload),
    };
}

