/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceEntityItemListLinks } from './ReferenceEntityItemListLinks';
import {
    ReferenceEntityItemListLinksFromJSON,
    ReferenceEntityItemListLinksFromJSONTyped,
    ReferenceEntityItemListLinksToJSON,
} from './ReferenceEntityItemListLinks';

/**
 * 
 * @export
 * @interface ReferenceEntityItemList
 */
export interface ReferenceEntityItemList {
    /**
     * 
     * @type {ReferenceEntityItemListLinks}
     * @memberof ReferenceEntityItemList
     */
    links?: ReferenceEntityItemListLinks;
}

/**
 * Check if a given object implements the ReferenceEntityItemList interface.
 */
export function instanceOfReferenceEntityItemList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferenceEntityItemListFromJSON(json: any): ReferenceEntityItemList {
    return ReferenceEntityItemListFromJSONTyped(json, false);
}

export function ReferenceEntityItemListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntityItemList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, '_links') ? undefined : ReferenceEntityItemListLinksFromJSON(json['_links']),
    };
}

export function ReferenceEntityItemListToJSON(value?: ReferenceEntityItemList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_links': ReferenceEntityItemListLinksToJSON(value.links),
    };
}

