/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInner } from './ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInner';
import {
    ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInnerFromJSON,
    ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInnerFromJSONTyped,
    ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInnerToJSON,
} from './ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInner';

/**
 * Record attributes values, see <a href='/concepts/reference-entities.html#focus-on-the-reference-entity-record-values'>Reference entity record values</a> section for more details
 * @export
 * @interface ReferenceEntityRecordEmbeddedItemsInnerAllOfValues
 */
export interface ReferenceEntityRecordEmbeddedItemsInnerAllOfValues {
    /**
     * 
     * @type {Array<ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInner>}
     * @memberof ReferenceEntityRecordEmbeddedItemsInnerAllOfValues
     */
    additionalProperties?: Array<ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInner>;
}

/**
 * Check if a given object implements the ReferenceEntityRecordEmbeddedItemsInnerAllOfValues interface.
 */
export function instanceOfReferenceEntityRecordEmbeddedItemsInnerAllOfValues(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesFromJSON(json: any): ReferenceEntityRecordEmbeddedItemsInnerAllOfValues {
    return ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesFromJSONTyped(json, false);
}

export function ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntityRecordEmbeddedItemsInnerAllOfValues {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'additionalProperties': !exists(json, 'additionalProperties') ? undefined : ((json['additionalProperties'] as Array<any>).map(ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInnerFromJSON)),
    };
}

export function ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesToJSON(value?: ReferenceEntityRecordEmbeddedItemsInnerAllOfValues | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'additionalProperties': value.additionalProperties === undefined ? undefined : ((value.additionalProperties as Array<any>).map(ReferenceEntityRecordEmbeddedItemsInnerAllOfValuesAdditionalPropertiesInnerToJSON)),
    };
}

