/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceEntityRecordListAllOfValuesAttributeCode } from './ReferenceEntityRecordListAllOfValuesAttributeCode';
import {
    ReferenceEntityRecordListAllOfValuesAttributeCodeFromJSON,
    ReferenceEntityRecordListAllOfValuesAttributeCodeFromJSONTyped,
    ReferenceEntityRecordListAllOfValuesAttributeCodeToJSON,
} from './ReferenceEntityRecordListAllOfValuesAttributeCode';

/**
 * Record attributes values, see <a href='/concepts/reference-entities.html#focus-on-the-reference-entity-record-values'>Reference entity record values</a> section for more details
 * @export
 * @interface ReferenceEntityRecordListAllOfValues
 */
export interface ReferenceEntityRecordListAllOfValues {
    /**
     * 
     * @type {Array<ReferenceEntityRecordListAllOfValuesAttributeCode>}
     * @memberof ReferenceEntityRecordListAllOfValues
     */
    attributeCode?: Array<ReferenceEntityRecordListAllOfValuesAttributeCode>;
}

/**
 * Check if a given object implements the ReferenceEntityRecordListAllOfValues interface.
 */
export function instanceOfReferenceEntityRecordListAllOfValues(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferenceEntityRecordListAllOfValuesFromJSON(json: any): ReferenceEntityRecordListAllOfValues {
    return ReferenceEntityRecordListAllOfValuesFromJSONTyped(json, false);
}

export function ReferenceEntityRecordListAllOfValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntityRecordListAllOfValues {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributeCode': !exists(json, 'attributeCode') ? undefined : ((json['attributeCode'] as Array<any>).map(ReferenceEntityRecordListAllOfValuesAttributeCodeFromJSON)),
    };
}

export function ReferenceEntityRecordListAllOfValuesToJSON(value?: ReferenceEntityRecordListAllOfValues | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributeCode': value.attributeCode === undefined ? undefined : ((value.attributeCode as Array<any>).map(ReferenceEntityRecordListAllOfValuesAttributeCodeToJSON)),
    };
}

