/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceEntityListAllOfLinks } from './ReferenceEntityListAllOfLinks';
import {
    ReferenceEntityListAllOfLinksFromJSON,
    ReferenceEntityListAllOfLinksFromJSONTyped,
    ReferenceEntityListAllOfLinksToJSON,
} from './ReferenceEntityListAllOfLinks';

/**
 * 
 * @export
 * @interface ReferenceEntityListAllOf
 */
export interface ReferenceEntityListAllOf {
    /**
     * 
     * @type {ReferenceEntityListAllOfLinks}
     * @memberof ReferenceEntityListAllOf
     */
    links?: ReferenceEntityListAllOfLinks;
}

/**
 * Check if a given object implements the ReferenceEntityListAllOf interface.
 */
export function instanceOfReferenceEntityListAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReferenceEntityListAllOfFromJSON(json: any): ReferenceEntityListAllOf {
    return ReferenceEntityListAllOfFromJSONTyped(json, false);
}

export function ReferenceEntityListAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntityListAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, '_links') ? undefined : ReferenceEntityListAllOfLinksFromJSON(json['_links']),
    };
}

export function ReferenceEntityListAllOfToJSON(value?: ReferenceEntityListAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_links': ReferenceEntityListAllOfLinksToJSON(value.links),
    };
}

