/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceEntityAllOf1Labels } from './ReferenceEntityAllOf1Labels';
import {
    ReferenceEntityAllOf1LabelsFromJSON,
    ReferenceEntityAllOf1LabelsFromJSONTyped,
    ReferenceEntityAllOf1LabelsToJSON,
} from './ReferenceEntityAllOf1Labels';

/**
 * 
 * @export
 * @interface ReferenceEntityAllOf1
 */
export interface ReferenceEntityAllOf1 {
    /**
     * Reference entity code
     * @type {string}
     * @memberof ReferenceEntityAllOf1
     */
    code: string;
    /**
     * 
     * @type {ReferenceEntityAllOf1Labels}
     * @memberof ReferenceEntityAllOf1
     */
    labels?: ReferenceEntityAllOf1Labels;
    /**
     * Code of the reference entity image
     * @type {string}
     * @memberof ReferenceEntityAllOf1
     */
    image?: string;
}

/**
 * Check if a given object implements the ReferenceEntityAllOf1 interface.
 */
export function instanceOfReferenceEntityAllOf1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function ReferenceEntityAllOf1FromJSON(json: any): ReferenceEntityAllOf1 {
    return ReferenceEntityAllOf1FromJSONTyped(json, false);
}

export function ReferenceEntityAllOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntityAllOf1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'labels': !exists(json, 'labels') ? undefined : ReferenceEntityAllOf1LabelsFromJSON(json['labels']),
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function ReferenceEntityAllOf1ToJSON(value?: ReferenceEntityAllOf1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'labels': ReferenceEntityAllOf1LabelsToJSON(value.labels),
        'image': value.image,
    };
}

