/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceEntityAllOf1Labels } from './ReferenceEntityAllOf1Labels';
import {
    ReferenceEntityAllOf1LabelsFromJSON,
    ReferenceEntityAllOf1LabelsFromJSONTyped,
    ReferenceEntityAllOf1LabelsToJSON,
} from './ReferenceEntityAllOf1Labels';
import type { ReferenceEntityAllOfLinks } from './ReferenceEntityAllOfLinks';
import {
    ReferenceEntityAllOfLinksFromJSON,
    ReferenceEntityAllOfLinksFromJSONTyped,
    ReferenceEntityAllOfLinksToJSON,
} from './ReferenceEntityAllOfLinks';

/**
 * 
 * @export
 * @interface ReferenceEntity
 */
export interface ReferenceEntity {
    /**
     * 
     * @type {ReferenceEntityAllOfLinks}
     * @memberof ReferenceEntity
     */
    links?: ReferenceEntityAllOfLinks;
    /**
     * Reference entity code
     * @type {string}
     * @memberof ReferenceEntity
     */
    code: string;
    /**
     * 
     * @type {ReferenceEntityAllOf1Labels}
     * @memberof ReferenceEntity
     */
    labels?: ReferenceEntityAllOf1Labels;
    /**
     * Code of the reference entity image
     * @type {string}
     * @memberof ReferenceEntity
     */
    image?: string;
}

/**
 * Check if a given object implements the ReferenceEntity interface.
 */
export function instanceOfReferenceEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function ReferenceEntityFromJSON(json: any): ReferenceEntity {
    return ReferenceEntityFromJSONTyped(json, false);
}

export function ReferenceEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'links': !exists(json, '_links') ? undefined : ReferenceEntityAllOfLinksFromJSON(json['_links']),
        'code': json['code'],
        'labels': !exists(json, 'labels') ? undefined : ReferenceEntityAllOf1LabelsFromJSON(json['labels']),
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function ReferenceEntityToJSON(value?: ReferenceEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        '_links': ReferenceEntityAllOfLinksToJSON(value.links),
        'code': value.code,
        'labels': ReferenceEntityAllOf1LabelsToJSON(value.labels),
        'image': value.image,
    };
}

