/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReferenceEntitiesEmbeddedItemsInnerAllOf1Labels } from './ReferenceEntitiesEmbeddedItemsInnerAllOf1Labels';
import {
    ReferenceEntitiesEmbeddedItemsInnerAllOf1LabelsFromJSON,
    ReferenceEntitiesEmbeddedItemsInnerAllOf1LabelsFromJSONTyped,
    ReferenceEntitiesEmbeddedItemsInnerAllOf1LabelsToJSON,
} from './ReferenceEntitiesEmbeddedItemsInnerAllOf1Labels';

/**
 * 
 * @export
 * @interface ReferenceEntitiesEmbeddedItemsInnerAllOf1
 */
export interface ReferenceEntitiesEmbeddedItemsInnerAllOf1 {
    /**
     * Reference entity code
     * @type {string}
     * @memberof ReferenceEntitiesEmbeddedItemsInnerAllOf1
     */
    code: string;
    /**
     * 
     * @type {ReferenceEntitiesEmbeddedItemsInnerAllOf1Labels}
     * @memberof ReferenceEntitiesEmbeddedItemsInnerAllOf1
     */
    labels?: ReferenceEntitiesEmbeddedItemsInnerAllOf1Labels;
    /**
     * Code of the reference entity image
     * @type {string}
     * @memberof ReferenceEntitiesEmbeddedItemsInnerAllOf1
     */
    image?: string;
}

/**
 * Check if a given object implements the ReferenceEntitiesEmbeddedItemsInnerAllOf1 interface.
 */
export function instanceOfReferenceEntitiesEmbeddedItemsInnerAllOf1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function ReferenceEntitiesEmbeddedItemsInnerAllOf1FromJSON(json: any): ReferenceEntitiesEmbeddedItemsInnerAllOf1 {
    return ReferenceEntitiesEmbeddedItemsInnerAllOf1FromJSONTyped(json, false);
}

export function ReferenceEntitiesEmbeddedItemsInnerAllOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntitiesEmbeddedItemsInnerAllOf1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'labels': !exists(json, 'labels') ? undefined : ReferenceEntitiesEmbeddedItemsInnerAllOf1LabelsFromJSON(json['labels']),
        'image': !exists(json, 'image') ? undefined : json['image'],
    };
}

export function ReferenceEntitiesEmbeddedItemsInnerAllOf1ToJSON(value?: ReferenceEntitiesEmbeddedItemsInnerAllOf1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'labels': ReferenceEntitiesEmbeddedItemsInnerAllOf1LabelsToJSON(value.labels),
        'image': value.image,
    };
}

