/* tslint:disable */
/* eslint-disable */
/**
 * Akeneo PIM REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AttributeGroupsEmbeddedItemsInnerAllOfLabels } from './AttributeGroupsEmbeddedItemsInnerAllOfLabels';
import {
    AttributeGroupsEmbeddedItemsInnerAllOfLabelsFromJSON,
    AttributeGroupsEmbeddedItemsInnerAllOfLabelsFromJSONTyped,
    AttributeGroupsEmbeddedItemsInnerAllOfLabelsToJSON,
} from './AttributeGroupsEmbeddedItemsInnerAllOfLabels';

/**
 * 
 * @export
 * @interface SeveralAttributeGroupsPatchRequest
 */
export interface SeveralAttributeGroupsPatchRequest {
    /**
     * Attribute group code
     * @type {string}
     * @memberof SeveralAttributeGroupsPatchRequest
     */
    code: string;
    /**
     * Attribute group order among other attribute groups
     * @type {number}
     * @memberof SeveralAttributeGroupsPatchRequest
     */
    sortOrder?: number;
    /**
     * Attribute codes that compose the attribute group
     * @type {Array<string>}
     * @memberof SeveralAttributeGroupsPatchRequest
     */
    attributes?: Array<string>;
    /**
     * 
     * @type {AttributeGroupsEmbeddedItemsInnerAllOfLabels}
     * @memberof SeveralAttributeGroupsPatchRequest
     */
    labels?: AttributeGroupsEmbeddedItemsInnerAllOfLabels;
}

/**
 * Check if a given object implements the SeveralAttributeGroupsPatchRequest interface.
 */
export function instanceOfSeveralAttributeGroupsPatchRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "code" in value;

    return isInstance;
}

export function SeveralAttributeGroupsPatchRequestFromJSON(json: any): SeveralAttributeGroupsPatchRequest {
    return SeveralAttributeGroupsPatchRequestFromJSONTyped(json, false);
}

export function SeveralAttributeGroupsPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeveralAttributeGroupsPatchRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'sortOrder': !exists(json, 'sort_order') ? undefined : json['sort_order'],
        'attributes': !exists(json, 'attributes') ? undefined : json['attributes'],
        'labels': !exists(json, 'labels') ? undefined : AttributeGroupsEmbeddedItemsInnerAllOfLabelsFromJSON(json['labels']),
    };
}

export function SeveralAttributeGroupsPatchRequestToJSON(value?: SeveralAttributeGroupsPatchRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'sort_order': value.sortOrder,
        'attributes': value.attributes,
        'labels': AttributeGroupsEmbeddedItemsInnerAllOfLabelsToJSON(value.labels),
    };
}

